/*******************************************************************************
 * FACE Data Model to AADL Translator
 * 
 * Copyright 2018 Carnegie Mellon University. All Rights Reserved.
 * 
 * NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON
 * AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
 * AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY,
 * EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY
 * WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 * 
 * Released under an Eclipse Public License - v1.0-style license, please see license.txt or contact
 * permission@sei.cmu.edu for full terms.
 * 
 * [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.
 * Please see Copyright notice for non-US Government use and distribution.
 * 
 * DM18-0762
 *******************************************************************************/
package org.osate.simpleidl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SimpleIDLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Specification");
		private final Assignment cDefinitionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDefinitionsDefinitionParserRuleCall_0 = (RuleCall)cDefinitionsAssignment.eContents().get(0);
		
		///*
		// * This is a subset of IDL 4.2. It is intended to be used to parse IDL files generated from the FACE Conformance Test
		// * Suite 3.0. Portions of IDL which are not generated by the FACE CTS are not included in this subset.
		// * 
		// * In one case, FACE's version of IDL in the FACE standard disagrees with the IDL standard. In FACE, a union has an
		// * opening curly between the union's name and the "switch" keyword. It also has a corresponding closing curly and
		// * semicolon at the end of the union. These are not in the IDL standard. This subset follows the FACE standard for
		// * unions and deviates from the IDL standard.
		// * 
		// * The comments on each grammar rule in this file contain the relevant syntax definitions from the IDL standard's
		// * Annex A: Consolidated IDL Grammar.
		// */ /*
		// * (1) <specification> ::= <definition>+
		// */ Specification:
		//	definitions+=Definition+;
		@Override public ParserRule getRule() { return rule; }
		
		//definitions+=Definition+
		public Assignment getDefinitionsAssignment() { return cDefinitionsAssignment; }
		
		//Definition
		public RuleCall getDefinitionsDefinitionParserRuleCall_0() { return cDefinitionsDefinitionParserRuleCall_0; }
	}
	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Definition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNamedDefinitionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cStructForwardAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cStructKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cStructAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cStructStructCrossReference_1_2_0 = (CrossReference)cStructAssignment_1_2.eContents().get(0);
		private final RuleCall cStructStructIDTerminalRuleCall_1_2_0_1 = (RuleCall)cStructStructCrossReference_1_2_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		///*
		// * (2) <definition> ::= <module_dcl> ";"
		// *                  | <const_dcl> ";"
		// *                  | <type_dcl> ";"
		// * (20) <type_dcl> ::= <constr_type_dcl>
		// *                 | <native_dcl>
		// *                 | <typedef_dcl>
		// * (44) <constr_type_dcl> ::= <struct_dcl>
		// *                        | <union_dcl>
		// *                        | <enum_dcl>
		// * (45) <struct_dcl> ::= <struct_def>
		// *                   | <struct_forward_dcl>
		// * (48) <struct_forward_dcl> ::= "struct" <identifier>
		// */ Definition:
		//	NamedDefinition | {StructForward} 'struct' struct=[Struct] ';';
		@Override public ParserRule getRule() { return rule; }
		
		//NamedDefinition | {StructForward} 'struct' struct=[Struct] ';'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NamedDefinition
		public RuleCall getNamedDefinitionParserRuleCall_0() { return cNamedDefinitionParserRuleCall_0; }
		
		//{StructForward} 'struct' struct=[Struct] ';'
		public Group getGroup_1() { return cGroup_1; }
		
		//{StructForward}
		public Action getStructForwardAction_1_0() { return cStructForwardAction_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_1_1() { return cStructKeyword_1_1; }
		
		//struct=[Struct]
		public Assignment getStructAssignment_1_2() { return cStructAssignment_1_2; }
		
		//[Struct]
		public CrossReference getStructStructCrossReference_1_2_0() { return cStructStructCrossReference_1_2_0; }
		
		//ID
		public RuleCall getStructStructIDTerminalRuleCall_1_2_0_1() { return cStructStructIDTerminalRuleCall_1_2_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }
	}
	public class NamedDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.NamedDefinition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cModuleAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cModuleKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cDefinitionsAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cDefinitionsDefinitionParserRuleCall_0_4_0 = (RuleCall)cDefinitionsAssignment_0_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_0_5 = (Keyword)cGroup_0.eContents().get(5);
		private final Keyword cSemicolonKeyword_0_6 = (Keyword)cGroup_0.eContents().get(6);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cStructAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cStructKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cNameAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_1_2_0 = (RuleCall)cNameAssignment_1_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cMembersAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cMembersMemberParserRuleCall_1_4_0 = (RuleCall)cMembersAssignment_1_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		private final Keyword cSemicolonKeyword_1_6 = (Keyword)cGroup_1.eContents().get(6);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cUnionAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cUnionKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cNameAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_2_0 = (RuleCall)cNameAssignment_2_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Keyword cSwitchKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_2_5 = (Keyword)cGroup_2.eContents().get(5);
		private final Keyword cUnsignedKeyword_2_6 = (Keyword)cGroup_2.eContents().get(6);
		private final Keyword cShortKeyword_2_7 = (Keyword)cGroup_2.eContents().get(7);
		private final Keyword cRightParenthesisKeyword_2_8 = (Keyword)cGroup_2.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_2_9 = (Keyword)cGroup_2.eContents().get(9);
		private final Assignment cCasesAssignment_2_10 = (Assignment)cGroup_2.eContents().get(10);
		private final RuleCall cCasesCaseParserRuleCall_2_10_0 = (RuleCall)cCasesAssignment_2_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_11 = (Keyword)cGroup_2.eContents().get(11);
		private final Keyword cSemicolonKeyword_2_12 = (Keyword)cGroup_2.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_2_13 = (Keyword)cGroup_2.eContents().get(13);
		private final Keyword cSemicolonKeyword_2_14 = (Keyword)cGroup_2.eContents().get(14);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cEnumAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cEnumKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cNameAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_3_2_0 = (RuleCall)cNameAssignment_3_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Assignment cLiteralsAssignment_3_4 = (Assignment)cGroup_3.eContents().get(4);
		private final RuleCall cLiteralsIDTerminalRuleCall_3_4_0 = (RuleCall)cLiteralsAssignment_3_4.eContents().get(0);
		private final Group cGroup_3_5 = (Group)cGroup_3.eContents().get(5);
		private final Keyword cCommaKeyword_3_5_0 = (Keyword)cGroup_3_5.eContents().get(0);
		private final Assignment cLiteralsAssignment_3_5_1 = (Assignment)cGroup_3_5.eContents().get(1);
		private final RuleCall cLiteralsIDTerminalRuleCall_3_5_1_0 = (RuleCall)cLiteralsAssignment_3_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_6 = (Keyword)cGroup_3.eContents().get(6);
		private final Keyword cSemicolonKeyword_3_7 = (Keyword)cGroup_3.eContents().get(7);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cArrayTypeAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cTypedefKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cTypeAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cTypeNamedDefinitionCrossReference_4_2_0 = (CrossReference)cTypeAssignment_4_2.eContents().get(0);
		private final RuleCall cTypeNamedDefinitionScopedNameParserRuleCall_4_2_0_1 = (RuleCall)cTypeNamedDefinitionCrossReference_4_2_0.eContents().get(1);
		private final Assignment cNameAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_4_3_0 = (RuleCall)cNameAssignment_4_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Assignment cSizeAssignment_4_5 = (Assignment)cGroup_4.eContents().get(5);
		private final RuleCall cSizeINTTerminalRuleCall_4_5_0 = (RuleCall)cSizeAssignment_4_5.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_6 = (Keyword)cGroup_4.eContents().get(6);
		private final Keyword cSemicolonKeyword_4_7 = (Keyword)cGroup_4.eContents().get(7);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cSignedShortIntAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cTypedefKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cShortKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cNameAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_5_3_0 = (RuleCall)cNameAssignment_5_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cSignedLongIntAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Keyword cTypedefKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cLongKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cNameAssignment_6_3 = (Assignment)cGroup_6.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_6_3_0 = (RuleCall)cNameAssignment_6_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cAlternatives.eContents().get(7);
		private final Action cSignedLongLongIntAction_7_0 = (Action)cGroup_7.eContents().get(0);
		private final Keyword cTypedefKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Keyword cLongKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Keyword cLongKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Assignment cNameAssignment_7_4 = (Assignment)cGroup_7.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_7_4_0 = (RuleCall)cNameAssignment_7_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_7_5 = (Keyword)cGroup_7.eContents().get(5);
		private final Group cGroup_8 = (Group)cAlternatives.eContents().get(8);
		private final Action cUnsignedShortIntAction_8_0 = (Action)cGroup_8.eContents().get(0);
		private final Keyword cTypedefKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cUnsignedKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Keyword cShortKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		private final Assignment cNameAssignment_8_4 = (Assignment)cGroup_8.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_8_4_0 = (RuleCall)cNameAssignment_8_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_8_5 = (Keyword)cGroup_8.eContents().get(5);
		private final Group cGroup_9 = (Group)cAlternatives.eContents().get(9);
		private final Action cUnsignedLongIntAction_9_0 = (Action)cGroup_9.eContents().get(0);
		private final Keyword cTypedefKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Keyword cUnsignedKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Keyword cLongKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Assignment cNameAssignment_9_4 = (Assignment)cGroup_9.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_9_4_0 = (RuleCall)cNameAssignment_9_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_9_5 = (Keyword)cGroup_9.eContents().get(5);
		private final Group cGroup_10 = (Group)cAlternatives.eContents().get(10);
		private final Action cUnsignedLongLongIntAction_10_0 = (Action)cGroup_10.eContents().get(0);
		private final Keyword cTypedefKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Keyword cUnsignedKeyword_10_2 = (Keyword)cGroup_10.eContents().get(2);
		private final Keyword cLongKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Keyword cLongKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Assignment cNameAssignment_10_5 = (Assignment)cGroup_10.eContents().get(5);
		private final RuleCall cNameIDTerminalRuleCall_10_5_0 = (RuleCall)cNameAssignment_10_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_10_6 = (Keyword)cGroup_10.eContents().get(6);
		private final Group cGroup_11 = (Group)cAlternatives.eContents().get(11);
		private final Action cFloatTypeAction_11_0 = (Action)cGroup_11.eContents().get(0);
		private final Keyword cTypedefKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Keyword cFloatKeyword_11_2 = (Keyword)cGroup_11.eContents().get(2);
		private final Assignment cNameAssignment_11_3 = (Assignment)cGroup_11.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_11_3_0 = (RuleCall)cNameAssignment_11_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Group cGroup_12 = (Group)cAlternatives.eContents().get(12);
		private final Action cDoubleTypeAction_12_0 = (Action)cGroup_12.eContents().get(0);
		private final Keyword cTypedefKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Keyword cDoubleKeyword_12_2 = (Keyword)cGroup_12.eContents().get(2);
		private final Assignment cNameAssignment_12_3 = (Assignment)cGroup_12.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_12_3_0 = (RuleCall)cNameAssignment_12_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Group cGroup_13 = (Group)cAlternatives.eContents().get(13);
		private final Action cLongDoubleTypeAction_13_0 = (Action)cGroup_13.eContents().get(0);
		private final Keyword cTypedefKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Keyword cLongKeyword_13_2 = (Keyword)cGroup_13.eContents().get(2);
		private final Keyword cDoubleKeyword_13_3 = (Keyword)cGroup_13.eContents().get(3);
		private final Assignment cNameAssignment_13_4 = (Assignment)cGroup_13.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_13_4_0 = (RuleCall)cNameAssignment_13_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_13_5 = (Keyword)cGroup_13.eContents().get(5);
		private final Group cGroup_14 = (Group)cAlternatives.eContents().get(14);
		private final Action cCharTypeAction_14_0 = (Action)cGroup_14.eContents().get(0);
		private final Keyword cTypedefKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Keyword cCharKeyword_14_2 = (Keyword)cGroup_14.eContents().get(2);
		private final Assignment cNameAssignment_14_3 = (Assignment)cGroup_14.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_14_3_0 = (RuleCall)cNameAssignment_14_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_14_4 = (Keyword)cGroup_14.eContents().get(4);
		private final Group cGroup_15 = (Group)cAlternatives.eContents().get(15);
		private final Action cWideCharTypeAction_15_0 = (Action)cGroup_15.eContents().get(0);
		private final Keyword cTypedefKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Keyword cWcharKeyword_15_2 = (Keyword)cGroup_15.eContents().get(2);
		private final Assignment cNameAssignment_15_3 = (Assignment)cGroup_15.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_15_3_0 = (RuleCall)cNameAssignment_15_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_15_4 = (Keyword)cGroup_15.eContents().get(4);
		private final Group cGroup_16 = (Group)cAlternatives.eContents().get(16);
		private final Action cBooleanTypeAction_16_0 = (Action)cGroup_16.eContents().get(0);
		private final Keyword cTypedefKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Keyword cBooleanKeyword_16_2 = (Keyword)cGroup_16.eContents().get(2);
		private final Assignment cNameAssignment_16_3 = (Assignment)cGroup_16.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_16_3_0 = (RuleCall)cNameAssignment_16_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_16_4 = (Keyword)cGroup_16.eContents().get(4);
		private final Group cGroup_17 = (Group)cAlternatives.eContents().get(17);
		private final Action cOctetTypeAction_17_0 = (Action)cGroup_17.eContents().get(0);
		private final Keyword cTypedefKeyword_17_1 = (Keyword)cGroup_17.eContents().get(1);
		private final Keyword cOctetKeyword_17_2 = (Keyword)cGroup_17.eContents().get(2);
		private final Assignment cNameAssignment_17_3 = (Assignment)cGroup_17.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_17_3_0 = (RuleCall)cNameAssignment_17_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_17_4 = (Keyword)cGroup_17.eContents().get(4);
		private final Group cGroup_18 = (Group)cAlternatives.eContents().get(18);
		private final Action cReferencedTypeAction_18_0 = (Action)cGroup_18.eContents().get(0);
		private final Keyword cTypedefKeyword_18_1 = (Keyword)cGroup_18.eContents().get(1);
		private final Assignment cTypeAssignment_18_2 = (Assignment)cGroup_18.eContents().get(2);
		private final CrossReference cTypeNamedDefinitionCrossReference_18_2_0 = (CrossReference)cTypeAssignment_18_2.eContents().get(0);
		private final RuleCall cTypeNamedDefinitionScopedNameParserRuleCall_18_2_0_1 = (RuleCall)cTypeNamedDefinitionCrossReference_18_2_0.eContents().get(1);
		private final Assignment cNameAssignment_18_3 = (Assignment)cGroup_18.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_18_3_0 = (RuleCall)cNameAssignment_18_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_18_4 = (Keyword)cGroup_18.eContents().get(4);
		private final Group cGroup_19 = (Group)cAlternatives.eContents().get(19);
		private final Action cBoundedSequenceAction_19_0 = (Action)cGroup_19.eContents().get(0);
		private final Keyword cTypedefKeyword_19_1 = (Keyword)cGroup_19.eContents().get(1);
		private final Keyword cSequenceKeyword_19_2 = (Keyword)cGroup_19.eContents().get(2);
		private final Keyword cLessThanSignKeyword_19_3 = (Keyword)cGroup_19.eContents().get(3);
		private final Assignment cTypeAssignment_19_4 = (Assignment)cGroup_19.eContents().get(4);
		private final CrossReference cTypeNamedDefinitionCrossReference_19_4_0 = (CrossReference)cTypeAssignment_19_4.eContents().get(0);
		private final RuleCall cTypeNamedDefinitionScopedNameParserRuleCall_19_4_0_1 = (RuleCall)cTypeNamedDefinitionCrossReference_19_4_0.eContents().get(1);
		private final Keyword cCommaKeyword_19_5 = (Keyword)cGroup_19.eContents().get(5);
		private final Assignment cSizeAssignment_19_6 = (Assignment)cGroup_19.eContents().get(6);
		private final RuleCall cSizeINTTerminalRuleCall_19_6_0 = (RuleCall)cSizeAssignment_19_6.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_19_7 = (Keyword)cGroup_19.eContents().get(7);
		private final Assignment cNameAssignment_19_8 = (Assignment)cGroup_19.eContents().get(8);
		private final RuleCall cNameIDTerminalRuleCall_19_8_0 = (RuleCall)cNameAssignment_19_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_19_9 = (Keyword)cGroup_19.eContents().get(9);
		private final Group cGroup_20 = (Group)cAlternatives.eContents().get(20);
		private final Action cUnboundedSequenceAction_20_0 = (Action)cGroup_20.eContents().get(0);
		private final Keyword cTypedefKeyword_20_1 = (Keyword)cGroup_20.eContents().get(1);
		private final Keyword cSequenceKeyword_20_2 = (Keyword)cGroup_20.eContents().get(2);
		private final Keyword cLessThanSignKeyword_20_3 = (Keyword)cGroup_20.eContents().get(3);
		private final Assignment cTypeAssignment_20_4 = (Assignment)cGroup_20.eContents().get(4);
		private final CrossReference cTypeNamedDefinitionCrossReference_20_4_0 = (CrossReference)cTypeAssignment_20_4.eContents().get(0);
		private final RuleCall cTypeNamedDefinitionScopedNameParserRuleCall_20_4_0_1 = (RuleCall)cTypeNamedDefinitionCrossReference_20_4_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_20_5 = (Keyword)cGroup_20.eContents().get(5);
		private final Assignment cNameAssignment_20_6 = (Assignment)cGroup_20.eContents().get(6);
		private final RuleCall cNameIDTerminalRuleCall_20_6_0 = (RuleCall)cNameAssignment_20_6.eContents().get(0);
		private final Keyword cSemicolonKeyword_20_7 = (Keyword)cGroup_20.eContents().get(7);
		private final Group cGroup_21 = (Group)cAlternatives.eContents().get(21);
		private final Action cBoundedStringAction_21_0 = (Action)cGroup_21.eContents().get(0);
		private final Keyword cTypedefKeyword_21_1 = (Keyword)cGroup_21.eContents().get(1);
		private final Keyword cStringKeyword_21_2 = (Keyword)cGroup_21.eContents().get(2);
		private final Keyword cLessThanSignKeyword_21_3 = (Keyword)cGroup_21.eContents().get(3);
		private final Assignment cSizeAssignment_21_4 = (Assignment)cGroup_21.eContents().get(4);
		private final RuleCall cSizeINTTerminalRuleCall_21_4_0 = (RuleCall)cSizeAssignment_21_4.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_21_5 = (Keyword)cGroup_21.eContents().get(5);
		private final Assignment cNameAssignment_21_6 = (Assignment)cGroup_21.eContents().get(6);
		private final RuleCall cNameIDTerminalRuleCall_21_6_0 = (RuleCall)cNameAssignment_21_6.eContents().get(0);
		private final Keyword cSemicolonKeyword_21_7 = (Keyword)cGroup_21.eContents().get(7);
		private final Group cGroup_22 = (Group)cAlternatives.eContents().get(22);
		private final Action cUnboundedStringAction_22_0 = (Action)cGroup_22.eContents().get(0);
		private final Keyword cTypedefKeyword_22_1 = (Keyword)cGroup_22.eContents().get(1);
		private final Keyword cStringKeyword_22_2 = (Keyword)cGroup_22.eContents().get(2);
		private final Assignment cNameAssignment_22_3 = (Assignment)cGroup_22.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_22_3_0 = (RuleCall)cNameAssignment_22_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_22_4 = (Keyword)cGroup_22.eContents().get(4);
		private final Group cGroup_23 = (Group)cAlternatives.eContents().get(23);
		private final Action cBoundedWideStringAction_23_0 = (Action)cGroup_23.eContents().get(0);
		private final Keyword cTypedefKeyword_23_1 = (Keyword)cGroup_23.eContents().get(1);
		private final Keyword cWstringKeyword_23_2 = (Keyword)cGroup_23.eContents().get(2);
		private final Keyword cLessThanSignKeyword_23_3 = (Keyword)cGroup_23.eContents().get(3);
		private final Assignment cSizeAssignment_23_4 = (Assignment)cGroup_23.eContents().get(4);
		private final RuleCall cSizeINTTerminalRuleCall_23_4_0 = (RuleCall)cSizeAssignment_23_4.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_23_5 = (Keyword)cGroup_23.eContents().get(5);
		private final Assignment cNameAssignment_23_6 = (Assignment)cGroup_23.eContents().get(6);
		private final RuleCall cNameIDTerminalRuleCall_23_6_0 = (RuleCall)cNameAssignment_23_6.eContents().get(0);
		private final Keyword cSemicolonKeyword_23_7 = (Keyword)cGroup_23.eContents().get(7);
		private final Group cGroup_24 = (Group)cAlternatives.eContents().get(24);
		private final Action cUnboundedWideStringAction_24_0 = (Action)cGroup_24.eContents().get(0);
		private final Keyword cTypedefKeyword_24_1 = (Keyword)cGroup_24.eContents().get(1);
		private final Keyword cWstringKeyword_24_2 = (Keyword)cGroup_24.eContents().get(2);
		private final Assignment cNameAssignment_24_3 = (Assignment)cGroup_24.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_24_3_0 = (RuleCall)cNameAssignment_24_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_24_4 = (Keyword)cGroup_24.eContents().get(4);
		private final Group cGroup_25 = (Group)cAlternatives.eContents().get(25);
		private final Action cFixedPtTypeAction_25_0 = (Action)cGroup_25.eContents().get(0);
		private final Keyword cTypedefKeyword_25_1 = (Keyword)cGroup_25.eContents().get(1);
		private final Keyword cFixedKeyword_25_2 = (Keyword)cGroup_25.eContents().get(2);
		private final Keyword cLessThanSignKeyword_25_3 = (Keyword)cGroup_25.eContents().get(3);
		private final Assignment cTotalDigitsAssignment_25_4 = (Assignment)cGroup_25.eContents().get(4);
		private final RuleCall cTotalDigitsINTTerminalRuleCall_25_4_0 = (RuleCall)cTotalDigitsAssignment_25_4.eContents().get(0);
		private final Keyword cCommaKeyword_25_5 = (Keyword)cGroup_25.eContents().get(5);
		private final Assignment cFractionalDigitsAssignment_25_6 = (Assignment)cGroup_25.eContents().get(6);
		private final RuleCall cFractionalDigitsINTTerminalRuleCall_25_6_0 = (RuleCall)cFractionalDigitsAssignment_25_6.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_25_7 = (Keyword)cGroup_25.eContents().get(7);
		private final Assignment cNameAssignment_25_8 = (Assignment)cGroup_25.eContents().get(8);
		private final RuleCall cNameIDTerminalRuleCall_25_8_0 = (RuleCall)cNameAssignment_25_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_25_9 = (Keyword)cGroup_25.eContents().get(9);
		
		///*
		// * (2) <definition> ::= <module_dcl> ";"
		// *                  | <const_dcl> ";"
		// *                  | <type_dcl> ";"
		// * (3) <module_dcl> ::= "module" <identifier> "{" <definition>+ "}"
		// * (20) <type_dcl> ::= <constr_type_dcl>
		// *                 | <native_dcl>
		// *                 | <typedef_dcl>
		// * (21) <type_spec> ::= <simple_type_spec>
		// * (22) <simple_type_spec> ::= <base_type_spec>
		// *                         | <scoped_name>
		// * (23) <base_type_spec> ::= <integer_type>
		// *                       | <floating_pt_type>
		// *                       | <char_type>
		// *                       | <wide_char_type>
		// *                       | <boolean_type>
		// *                       | <octet_type>
		// * (24) <floating_pt_type> ::= "float"
		// *                         | "double"
		// *                         | "long" "double"
		// * (25) <integer_type> ::= <signed_int>
		// *                     | <unsigned_int>
		// * (26) <signed_int> ::= <signed_short_int>
		// *                   | <signed_long_int>
		// *                   | <signed_longlong_int>
		// * (27) <signed_short_int> ::= "short"
		// * (28) <signed_long_int> ::= "long"
		// * (29) <signed_longlong_int> ::= "long" "long"
		// * (30) <unsigned_int> ::= <unsigned_short_int>
		// *                     | <unsigned_long_int>
		// *                     | <unsigned_longlong_int>
		// * (31) <unsigned_short_int> ::= "unsigned" "short"
		// * (32) <unsigned_long_int> ::= "unsigned" "long"
		// * (33) <unsigned_longlong_int> ::= "unsigned" "long" "long"
		// * (34) <char_type> ::= "char"
		// * (35) <wide_char_type> ::= "wchar"
		// * (36) <boolean_type> ::= "boolean"
		// * (37) <octet_type> ::= "octet"
		// * (38) <template_type_spec> ::= <sequence_type>
		// *                           | <string_type>
		// *                           | <wide_string_type>
		// *                           | <fixed_pt_type>
		// * (39) <sequence_type> ::= "sequence" "<" <type_spec> "," <positive_int_const> ">"
		// *                      | "sequence" "<" <type_spec> ">"
		// * (40) <string_type> ::= "string" "<" <positive_int_const> ">"
		// *                    | "string"
		// * (41) <wide_string_type> ::= "wstring" "<" <positive_int_const> ">"
		// *                         | "wstring"
		// * (42) <fixed_pt_type> ::= "fixed" "<" <positive_int_const> "," <positive_int_const> ">"
		// * (44) <constr_type_dcl> ::= <struct_dcl>
		// *                        | <union_dcl>
		// *                        | <enum_dcl>
		// * (45) <struct_dcl> ::= <struct_def>
		// *                   | <struct_forward_dcl>
		// * (46) <struct_def> ::= "struct" <identifier> "{" <member>+ "}"
		// * (49) <union_dcl> ::= <union_def>
		// *                  | <union_forward_dcl>
		// * (50) <union_def> ::= "union" <identifier> "switch" "(" <switch_type_spec> ")"
		// *                      "{" <switch_body> "}"
		// * (51) <switch_type_spec> ::= <integer_type>
		// *                         | <char_type>
		// *                         | <boolean_type>
		// *                         | <scoped_name>
		// * (52) <switch_body> ::= <case>+
		// * (57) <enum_dcl> ::= "enum" <identifier>
		// *                     "{" <enumerator> { "," <enumerator> } * "}"
		// * (58) <enumerator> ::= <identifier>
		// * (59) <array_declarator> ::= <identifier> <fixed_array_size>+
		// * (60) <fixed_array_size> ::= "[" <positive_int_const> "]"
		// * (62) <simple_declarator> ::= <identifier>
		// * (63) <typedef_dcl> ::= "typedef" <type_declarator>
		// * (64) <type_declarator> ::= { <simple_type_spec>
		// *                            | <template_type_spec>
		// *                            | <constr_type_dcl>
		// *                            } <any_declarators>
		// * (65) <any_declarators> ::= <any_declarator> { "," <any_declarator> }*
		// * (66) <any_declarator> ::= <simple_declarator>
		// *                       | <array_declarator>
		// */ NamedDefinition:
		//	{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';' | {Struct} 'struct' name=ID '{' members+=Member+ '}'
		//	';' | {Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')' '{' cases+=Case+ '}' ';' '}' ';' | {Enum} 'enum'
		//	name=ID '{' literals+=ID (',' literals+=ID)* '}' ';' | {ArrayType} 'typedef' type=[NamedDefinition|ScopedName] name=ID
		//	'[' size=INT ']' ';' | {SignedShortInt} 'typedef' 'short' name=ID ';' | {SignedLongInt} 'typedef' 'long' name=ID ';' |
		//	{SignedLongLongInt} 'typedef' 'long' 'long' name=ID ';' | {UnsignedShortInt} 'typedef' 'unsigned' 'short' name=ID ';'
		//	| {UnsignedLongInt} 'typedef' 'unsigned' 'long' name=ID ';' | {UnsignedLongLongInt} 'typedef' 'unsigned' 'long' 'long'
		//	name=ID ';' | {FloatType} 'typedef' 'float' name=ID ';' | {DoubleType} 'typedef' 'double' name=ID ';' |
		//	{LongDoubleType} 'typedef' 'long' 'double' name=ID ';' | {CharType} 'typedef' 'char' name=ID ';' | {WideCharType}
		//	'typedef' 'wchar' name=ID ';' | {BooleanType} 'typedef' 'boolean' name=ID ';' | {OctetType} 'typedef' 'octet' name=ID
		//	';' | {ReferencedType} 'typedef' type=[NamedDefinition|ScopedName] name=ID ';' | {BoundedSequence} 'typedef'
		//	'sequence' '<' type=[NamedDefinition|ScopedName] ',' size=INT '>' name=ID ';' | {UnboundedSequence} 'typedef'
		//	'sequence' '<' type=[NamedDefinition|ScopedName] '>' name=ID ';' | {BoundedString} 'typedef' 'string' '<' size=INT '>'
		//	name=ID ';' | {UnboundedString} 'typedef' 'string' name=ID ';' | {BoundedWideString} 'typedef' 'wstring' '<' size=INT
		//	'>' name=ID ';' | {UnboundedWideString} 'typedef' 'wstring' name=ID ';' | {FixedPtType} 'typedef' 'fixed' '<'
		//	totalDigits=INT ',' fractionalDigits=INT '>' name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';' | {Struct} 'struct' name=ID '{' members+=Member+ '}' ';'
		//| {Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')' '{' cases+=Case+ '}' ';' '}' ';' | {Enum} 'enum'
		//name=ID '{' literals+=ID (',' literals+=ID)* '}' ';' | {ArrayType} 'typedef' type=[NamedDefinition|ScopedName] name=ID
		//'[' size=INT ']' ';' | {SignedShortInt} 'typedef' 'short' name=ID ';' | {SignedLongInt} 'typedef' 'long' name=ID ';' |
		//{SignedLongLongInt} 'typedef' 'long' 'long' name=ID ';' | {UnsignedShortInt} 'typedef' 'unsigned' 'short' name=ID ';' |
		//{UnsignedLongInt} 'typedef' 'unsigned' 'long' name=ID ';' | {UnsignedLongLongInt} 'typedef' 'unsigned' 'long' 'long'
		//name=ID ';' | {FloatType} 'typedef' 'float' name=ID ';' | {DoubleType} 'typedef' 'double' name=ID ';' |
		//{LongDoubleType} 'typedef' 'long' 'double' name=ID ';' | {CharType} 'typedef' 'char' name=ID ';' | {WideCharType}
		//'typedef' 'wchar' name=ID ';' | {BooleanType} 'typedef' 'boolean' name=ID ';' | {OctetType} 'typedef' 'octet' name=ID
		//';' | {ReferencedType} 'typedef' type=[NamedDefinition|ScopedName] name=ID ';' | {BoundedSequence} 'typedef' 'sequence'
		//'<' type=[NamedDefinition|ScopedName] ',' size=INT '>' name=ID ';' | {UnboundedSequence} 'typedef' 'sequence' '<'
		//type=[NamedDefinition|ScopedName] '>' name=ID ';' | {BoundedString} 'typedef' 'string' '<' size=INT '>' name=ID ';' |
		//{UnboundedString} 'typedef' 'string' name=ID ';' | {BoundedWideString} 'typedef' 'wstring' '<' size=INT '>' name=ID ';'
		//| {UnboundedWideString} 'typedef' 'wstring' name=ID ';' | {FixedPtType} 'typedef' 'fixed' '<' totalDigits=INT ','
		//fractionalDigits=INT '>' name=ID ';'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Module}
		public Action getModuleAction_0_0() { return cModuleAction_0_0; }
		
		//'module'
		public Keyword getModuleKeyword_0_1() { return cModuleKeyword_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0_3() { return cLeftCurlyBracketKeyword_0_3; }
		
		//definitions+=Definition+
		public Assignment getDefinitionsAssignment_0_4() { return cDefinitionsAssignment_0_4; }
		
		//Definition
		public RuleCall getDefinitionsDefinitionParserRuleCall_0_4_0() { return cDefinitionsDefinitionParserRuleCall_0_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_0_5() { return cRightCurlyBracketKeyword_0_5; }
		
		//';'
		public Keyword getSemicolonKeyword_0_6() { return cSemicolonKeyword_0_6; }
		
		//{Struct} 'struct' name=ID '{' members+=Member+ '}' ';'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Struct}
		public Action getStructAction_1_0() { return cStructAction_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_1_1() { return cStructKeyword_1_1; }
		
		//name=ID
		public Assignment getNameAssignment_1_2() { return cNameAssignment_1_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_2_0() { return cNameIDTerminalRuleCall_1_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_3() { return cLeftCurlyBracketKeyword_1_3; }
		
		//members+=Member+
		public Assignment getMembersAssignment_1_4() { return cMembersAssignment_1_4; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_1_4_0() { return cMembersMemberParserRuleCall_1_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_5() { return cRightCurlyBracketKeyword_1_5; }
		
		//';'
		public Keyword getSemicolonKeyword_1_6() { return cSemicolonKeyword_1_6; }
		
		//{Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')' '{' cases+=Case+ '}' ';' '}' ';'
		public Group getGroup_2() { return cGroup_2; }
		
		//{Union}
		public Action getUnionAction_2_0() { return cUnionAction_2_0; }
		
		//'union'
		public Keyword getUnionKeyword_2_1() { return cUnionKeyword_2_1; }
		
		//name=ID
		public Assignment getNameAssignment_2_2() { return cNameAssignment_2_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_2_0() { return cNameIDTerminalRuleCall_2_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_3() { return cLeftCurlyBracketKeyword_2_3; }
		
		//'switch'
		public Keyword getSwitchKeyword_2_4() { return cSwitchKeyword_2_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_5() { return cLeftParenthesisKeyword_2_5; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_2_6() { return cUnsignedKeyword_2_6; }
		
		//'short'
		public Keyword getShortKeyword_2_7() { return cShortKeyword_2_7; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_8() { return cRightParenthesisKeyword_2_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_9() { return cLeftCurlyBracketKeyword_2_9; }
		
		//cases+=Case+
		public Assignment getCasesAssignment_2_10() { return cCasesAssignment_2_10; }
		
		//Case
		public RuleCall getCasesCaseParserRuleCall_2_10_0() { return cCasesCaseParserRuleCall_2_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_11() { return cRightCurlyBracketKeyword_2_11; }
		
		//';'
		public Keyword getSemicolonKeyword_2_12() { return cSemicolonKeyword_2_12; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_13() { return cRightCurlyBracketKeyword_2_13; }
		
		//';'
		public Keyword getSemicolonKeyword_2_14() { return cSemicolonKeyword_2_14; }
		
		//{Enum} 'enum' name=ID '{' literals+=ID (',' literals+=ID)* '}' ';'
		public Group getGroup_3() { return cGroup_3; }
		
		//{Enum}
		public Action getEnumAction_3_0() { return cEnumAction_3_0; }
		
		//'enum'
		public Keyword getEnumKeyword_3_1() { return cEnumKeyword_3_1; }
		
		//name=ID
		public Assignment getNameAssignment_3_2() { return cNameAssignment_3_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_2_0() { return cNameIDTerminalRuleCall_3_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_3() { return cLeftCurlyBracketKeyword_3_3; }
		
		//literals+=ID
		public Assignment getLiteralsAssignment_3_4() { return cLiteralsAssignment_3_4; }
		
		//ID
		public RuleCall getLiteralsIDTerminalRuleCall_3_4_0() { return cLiteralsIDTerminalRuleCall_3_4_0; }
		
		//(',' literals+=ID)*
		public Group getGroup_3_5() { return cGroup_3_5; }
		
		//','
		public Keyword getCommaKeyword_3_5_0() { return cCommaKeyword_3_5_0; }
		
		//literals+=ID
		public Assignment getLiteralsAssignment_3_5_1() { return cLiteralsAssignment_3_5_1; }
		
		//ID
		public RuleCall getLiteralsIDTerminalRuleCall_3_5_1_0() { return cLiteralsIDTerminalRuleCall_3_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_6() { return cRightCurlyBracketKeyword_3_6; }
		
		//';'
		public Keyword getSemicolonKeyword_3_7() { return cSemicolonKeyword_3_7; }
		
		//{ArrayType} 'typedef' type=[NamedDefinition|ScopedName] name=ID '[' size=INT ']' ';'
		public Group getGroup_4() { return cGroup_4; }
		
		//{ArrayType}
		public Action getArrayTypeAction_4_0() { return cArrayTypeAction_4_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_4_1() { return cTypedefKeyword_4_1; }
		
		//type=[NamedDefinition|ScopedName]
		public Assignment getTypeAssignment_4_2() { return cTypeAssignment_4_2; }
		
		//[NamedDefinition|ScopedName]
		public CrossReference getTypeNamedDefinitionCrossReference_4_2_0() { return cTypeNamedDefinitionCrossReference_4_2_0; }
		
		//ScopedName
		public RuleCall getTypeNamedDefinitionScopedNameParserRuleCall_4_2_0_1() { return cTypeNamedDefinitionScopedNameParserRuleCall_4_2_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_4_3() { return cNameAssignment_4_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_3_0() { return cNameIDTerminalRuleCall_4_3_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_4_4() { return cLeftSquareBracketKeyword_4_4; }
		
		//size=INT
		public Assignment getSizeAssignment_4_5() { return cSizeAssignment_4_5; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_4_5_0() { return cSizeINTTerminalRuleCall_4_5_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4_6() { return cRightSquareBracketKeyword_4_6; }
		
		//';'
		public Keyword getSemicolonKeyword_4_7() { return cSemicolonKeyword_4_7; }
		
		//{SignedShortInt} 'typedef' 'short' name=ID ';'
		public Group getGroup_5() { return cGroup_5; }
		
		//{SignedShortInt}
		public Action getSignedShortIntAction_5_0() { return cSignedShortIntAction_5_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_5_1() { return cTypedefKeyword_5_1; }
		
		//'short'
		public Keyword getShortKeyword_5_2() { return cShortKeyword_5_2; }
		
		//name=ID
		public Assignment getNameAssignment_5_3() { return cNameAssignment_5_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_5_3_0() { return cNameIDTerminalRuleCall_5_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_4() { return cSemicolonKeyword_5_4; }
		
		//{SignedLongInt} 'typedef' 'long' name=ID ';'
		public Group getGroup_6() { return cGroup_6; }
		
		//{SignedLongInt}
		public Action getSignedLongIntAction_6_0() { return cSignedLongIntAction_6_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_6_1() { return cTypedefKeyword_6_1; }
		
		//'long'
		public Keyword getLongKeyword_6_2() { return cLongKeyword_6_2; }
		
		//name=ID
		public Assignment getNameAssignment_6_3() { return cNameAssignment_6_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_6_3_0() { return cNameIDTerminalRuleCall_6_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6_4() { return cSemicolonKeyword_6_4; }
		
		//{SignedLongLongInt} 'typedef' 'long' 'long' name=ID ';'
		public Group getGroup_7() { return cGroup_7; }
		
		//{SignedLongLongInt}
		public Action getSignedLongLongIntAction_7_0() { return cSignedLongLongIntAction_7_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_7_1() { return cTypedefKeyword_7_1; }
		
		//'long'
		public Keyword getLongKeyword_7_2() { return cLongKeyword_7_2; }
		
		//'long'
		public Keyword getLongKeyword_7_3() { return cLongKeyword_7_3; }
		
		//name=ID
		public Assignment getNameAssignment_7_4() { return cNameAssignment_7_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_7_4_0() { return cNameIDTerminalRuleCall_7_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7_5() { return cSemicolonKeyword_7_5; }
		
		//{UnsignedShortInt} 'typedef' 'unsigned' 'short' name=ID ';'
		public Group getGroup_8() { return cGroup_8; }
		
		//{UnsignedShortInt}
		public Action getUnsignedShortIntAction_8_0() { return cUnsignedShortIntAction_8_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_8_1() { return cTypedefKeyword_8_1; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_8_2() { return cUnsignedKeyword_8_2; }
		
		//'short'
		public Keyword getShortKeyword_8_3() { return cShortKeyword_8_3; }
		
		//name=ID
		public Assignment getNameAssignment_8_4() { return cNameAssignment_8_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_8_4_0() { return cNameIDTerminalRuleCall_8_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_8_5() { return cSemicolonKeyword_8_5; }
		
		//{UnsignedLongInt} 'typedef' 'unsigned' 'long' name=ID ';'
		public Group getGroup_9() { return cGroup_9; }
		
		//{UnsignedLongInt}
		public Action getUnsignedLongIntAction_9_0() { return cUnsignedLongIntAction_9_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_9_1() { return cTypedefKeyword_9_1; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_9_2() { return cUnsignedKeyword_9_2; }
		
		//'long'
		public Keyword getLongKeyword_9_3() { return cLongKeyword_9_3; }
		
		//name=ID
		public Assignment getNameAssignment_9_4() { return cNameAssignment_9_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_9_4_0() { return cNameIDTerminalRuleCall_9_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9_5() { return cSemicolonKeyword_9_5; }
		
		//{UnsignedLongLongInt} 'typedef' 'unsigned' 'long' 'long' name=ID ';'
		public Group getGroup_10() { return cGroup_10; }
		
		//{UnsignedLongLongInt}
		public Action getUnsignedLongLongIntAction_10_0() { return cUnsignedLongLongIntAction_10_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_10_1() { return cTypedefKeyword_10_1; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_10_2() { return cUnsignedKeyword_10_2; }
		
		//'long'
		public Keyword getLongKeyword_10_3() { return cLongKeyword_10_3; }
		
		//'long'
		public Keyword getLongKeyword_10_4() { return cLongKeyword_10_4; }
		
		//name=ID
		public Assignment getNameAssignment_10_5() { return cNameAssignment_10_5; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_10_5_0() { return cNameIDTerminalRuleCall_10_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_10_6() { return cSemicolonKeyword_10_6; }
		
		//{FloatType} 'typedef' 'float' name=ID ';'
		public Group getGroup_11() { return cGroup_11; }
		
		//{FloatType}
		public Action getFloatTypeAction_11_0() { return cFloatTypeAction_11_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_11_1() { return cTypedefKeyword_11_1; }
		
		//'float'
		public Keyword getFloatKeyword_11_2() { return cFloatKeyword_11_2; }
		
		//name=ID
		public Assignment getNameAssignment_11_3() { return cNameAssignment_11_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_11_3_0() { return cNameIDTerminalRuleCall_11_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_11_4() { return cSemicolonKeyword_11_4; }
		
		//{DoubleType} 'typedef' 'double' name=ID ';'
		public Group getGroup_12() { return cGroup_12; }
		
		//{DoubleType}
		public Action getDoubleTypeAction_12_0() { return cDoubleTypeAction_12_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_12_1() { return cTypedefKeyword_12_1; }
		
		//'double'
		public Keyword getDoubleKeyword_12_2() { return cDoubleKeyword_12_2; }
		
		//name=ID
		public Assignment getNameAssignment_12_3() { return cNameAssignment_12_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_12_3_0() { return cNameIDTerminalRuleCall_12_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_12_4() { return cSemicolonKeyword_12_4; }
		
		//{LongDoubleType} 'typedef' 'long' 'double' name=ID ';'
		public Group getGroup_13() { return cGroup_13; }
		
		//{LongDoubleType}
		public Action getLongDoubleTypeAction_13_0() { return cLongDoubleTypeAction_13_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_13_1() { return cTypedefKeyword_13_1; }
		
		//'long'
		public Keyword getLongKeyword_13_2() { return cLongKeyword_13_2; }
		
		//'double'
		public Keyword getDoubleKeyword_13_3() { return cDoubleKeyword_13_3; }
		
		//name=ID
		public Assignment getNameAssignment_13_4() { return cNameAssignment_13_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_13_4_0() { return cNameIDTerminalRuleCall_13_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_13_5() { return cSemicolonKeyword_13_5; }
		
		//{CharType} 'typedef' 'char' name=ID ';'
		public Group getGroup_14() { return cGroup_14; }
		
		//{CharType}
		public Action getCharTypeAction_14_0() { return cCharTypeAction_14_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_14_1() { return cTypedefKeyword_14_1; }
		
		//'char'
		public Keyword getCharKeyword_14_2() { return cCharKeyword_14_2; }
		
		//name=ID
		public Assignment getNameAssignment_14_3() { return cNameAssignment_14_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_14_3_0() { return cNameIDTerminalRuleCall_14_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_14_4() { return cSemicolonKeyword_14_4; }
		
		//{WideCharType} 'typedef' 'wchar' name=ID ';'
		public Group getGroup_15() { return cGroup_15; }
		
		//{WideCharType}
		public Action getWideCharTypeAction_15_0() { return cWideCharTypeAction_15_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_15_1() { return cTypedefKeyword_15_1; }
		
		//'wchar'
		public Keyword getWcharKeyword_15_2() { return cWcharKeyword_15_2; }
		
		//name=ID
		public Assignment getNameAssignment_15_3() { return cNameAssignment_15_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_15_3_0() { return cNameIDTerminalRuleCall_15_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_15_4() { return cSemicolonKeyword_15_4; }
		
		//{BooleanType} 'typedef' 'boolean' name=ID ';'
		public Group getGroup_16() { return cGroup_16; }
		
		//{BooleanType}
		public Action getBooleanTypeAction_16_0() { return cBooleanTypeAction_16_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_16_1() { return cTypedefKeyword_16_1; }
		
		//'boolean'
		public Keyword getBooleanKeyword_16_2() { return cBooleanKeyword_16_2; }
		
		//name=ID
		public Assignment getNameAssignment_16_3() { return cNameAssignment_16_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_16_3_0() { return cNameIDTerminalRuleCall_16_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_16_4() { return cSemicolonKeyword_16_4; }
		
		//{OctetType} 'typedef' 'octet' name=ID ';'
		public Group getGroup_17() { return cGroup_17; }
		
		//{OctetType}
		public Action getOctetTypeAction_17_0() { return cOctetTypeAction_17_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_17_1() { return cTypedefKeyword_17_1; }
		
		//'octet'
		public Keyword getOctetKeyword_17_2() { return cOctetKeyword_17_2; }
		
		//name=ID
		public Assignment getNameAssignment_17_3() { return cNameAssignment_17_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_17_3_0() { return cNameIDTerminalRuleCall_17_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_17_4() { return cSemicolonKeyword_17_4; }
		
		//{ReferencedType} 'typedef' type=[NamedDefinition|ScopedName] name=ID ';'
		public Group getGroup_18() { return cGroup_18; }
		
		//{ReferencedType}
		public Action getReferencedTypeAction_18_0() { return cReferencedTypeAction_18_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_18_1() { return cTypedefKeyword_18_1; }
		
		//type=[NamedDefinition|ScopedName]
		public Assignment getTypeAssignment_18_2() { return cTypeAssignment_18_2; }
		
		//[NamedDefinition|ScopedName]
		public CrossReference getTypeNamedDefinitionCrossReference_18_2_0() { return cTypeNamedDefinitionCrossReference_18_2_0; }
		
		//ScopedName
		public RuleCall getTypeNamedDefinitionScopedNameParserRuleCall_18_2_0_1() { return cTypeNamedDefinitionScopedNameParserRuleCall_18_2_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_18_3() { return cNameAssignment_18_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_18_3_0() { return cNameIDTerminalRuleCall_18_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_18_4() { return cSemicolonKeyword_18_4; }
		
		//{BoundedSequence} 'typedef' 'sequence' '<' type=[NamedDefinition|ScopedName] ',' size=INT '>' name=ID ';'
		public Group getGroup_19() { return cGroup_19; }
		
		//{BoundedSequence}
		public Action getBoundedSequenceAction_19_0() { return cBoundedSequenceAction_19_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_19_1() { return cTypedefKeyword_19_1; }
		
		//'sequence'
		public Keyword getSequenceKeyword_19_2() { return cSequenceKeyword_19_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_19_3() { return cLessThanSignKeyword_19_3; }
		
		//type=[NamedDefinition|ScopedName]
		public Assignment getTypeAssignment_19_4() { return cTypeAssignment_19_4; }
		
		//[NamedDefinition|ScopedName]
		public CrossReference getTypeNamedDefinitionCrossReference_19_4_0() { return cTypeNamedDefinitionCrossReference_19_4_0; }
		
		//ScopedName
		public RuleCall getTypeNamedDefinitionScopedNameParserRuleCall_19_4_0_1() { return cTypeNamedDefinitionScopedNameParserRuleCall_19_4_0_1; }
		
		//','
		public Keyword getCommaKeyword_19_5() { return cCommaKeyword_19_5; }
		
		//size=INT
		public Assignment getSizeAssignment_19_6() { return cSizeAssignment_19_6; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_19_6_0() { return cSizeINTTerminalRuleCall_19_6_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_19_7() { return cGreaterThanSignKeyword_19_7; }
		
		//name=ID
		public Assignment getNameAssignment_19_8() { return cNameAssignment_19_8; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_19_8_0() { return cNameIDTerminalRuleCall_19_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_19_9() { return cSemicolonKeyword_19_9; }
		
		//{UnboundedSequence} 'typedef' 'sequence' '<' type=[NamedDefinition|ScopedName] '>' name=ID ';'
		public Group getGroup_20() { return cGroup_20; }
		
		//{UnboundedSequence}
		public Action getUnboundedSequenceAction_20_0() { return cUnboundedSequenceAction_20_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_20_1() { return cTypedefKeyword_20_1; }
		
		//'sequence'
		public Keyword getSequenceKeyword_20_2() { return cSequenceKeyword_20_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_20_3() { return cLessThanSignKeyword_20_3; }
		
		//type=[NamedDefinition|ScopedName]
		public Assignment getTypeAssignment_20_4() { return cTypeAssignment_20_4; }
		
		//[NamedDefinition|ScopedName]
		public CrossReference getTypeNamedDefinitionCrossReference_20_4_0() { return cTypeNamedDefinitionCrossReference_20_4_0; }
		
		//ScopedName
		public RuleCall getTypeNamedDefinitionScopedNameParserRuleCall_20_4_0_1() { return cTypeNamedDefinitionScopedNameParserRuleCall_20_4_0_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_20_5() { return cGreaterThanSignKeyword_20_5; }
		
		//name=ID
		public Assignment getNameAssignment_20_6() { return cNameAssignment_20_6; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_20_6_0() { return cNameIDTerminalRuleCall_20_6_0; }
		
		//';'
		public Keyword getSemicolonKeyword_20_7() { return cSemicolonKeyword_20_7; }
		
		//{BoundedString} 'typedef' 'string' '<' size=INT '>' name=ID ';'
		public Group getGroup_21() { return cGroup_21; }
		
		//{BoundedString}
		public Action getBoundedStringAction_21_0() { return cBoundedStringAction_21_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_21_1() { return cTypedefKeyword_21_1; }
		
		//'string'
		public Keyword getStringKeyword_21_2() { return cStringKeyword_21_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_21_3() { return cLessThanSignKeyword_21_3; }
		
		//size=INT
		public Assignment getSizeAssignment_21_4() { return cSizeAssignment_21_4; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_21_4_0() { return cSizeINTTerminalRuleCall_21_4_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_21_5() { return cGreaterThanSignKeyword_21_5; }
		
		//name=ID
		public Assignment getNameAssignment_21_6() { return cNameAssignment_21_6; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_21_6_0() { return cNameIDTerminalRuleCall_21_6_0; }
		
		//';'
		public Keyword getSemicolonKeyword_21_7() { return cSemicolonKeyword_21_7; }
		
		//{UnboundedString} 'typedef' 'string' name=ID ';'
		public Group getGroup_22() { return cGroup_22; }
		
		//{UnboundedString}
		public Action getUnboundedStringAction_22_0() { return cUnboundedStringAction_22_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_22_1() { return cTypedefKeyword_22_1; }
		
		//'string'
		public Keyword getStringKeyword_22_2() { return cStringKeyword_22_2; }
		
		//name=ID
		public Assignment getNameAssignment_22_3() { return cNameAssignment_22_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_22_3_0() { return cNameIDTerminalRuleCall_22_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_22_4() { return cSemicolonKeyword_22_4; }
		
		//{BoundedWideString} 'typedef' 'wstring' '<' size=INT '>' name=ID ';'
		public Group getGroup_23() { return cGroup_23; }
		
		//{BoundedWideString}
		public Action getBoundedWideStringAction_23_0() { return cBoundedWideStringAction_23_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_23_1() { return cTypedefKeyword_23_1; }
		
		//'wstring'
		public Keyword getWstringKeyword_23_2() { return cWstringKeyword_23_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_23_3() { return cLessThanSignKeyword_23_3; }
		
		//size=INT
		public Assignment getSizeAssignment_23_4() { return cSizeAssignment_23_4; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_23_4_0() { return cSizeINTTerminalRuleCall_23_4_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_23_5() { return cGreaterThanSignKeyword_23_5; }
		
		//name=ID
		public Assignment getNameAssignment_23_6() { return cNameAssignment_23_6; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_23_6_0() { return cNameIDTerminalRuleCall_23_6_0; }
		
		//';'
		public Keyword getSemicolonKeyword_23_7() { return cSemicolonKeyword_23_7; }
		
		//{UnboundedWideString} 'typedef' 'wstring' name=ID ';'
		public Group getGroup_24() { return cGroup_24; }
		
		//{UnboundedWideString}
		public Action getUnboundedWideStringAction_24_0() { return cUnboundedWideStringAction_24_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_24_1() { return cTypedefKeyword_24_1; }
		
		//'wstring'
		public Keyword getWstringKeyword_24_2() { return cWstringKeyword_24_2; }
		
		//name=ID
		public Assignment getNameAssignment_24_3() { return cNameAssignment_24_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_24_3_0() { return cNameIDTerminalRuleCall_24_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_24_4() { return cSemicolonKeyword_24_4; }
		
		//{FixedPtType} 'typedef' 'fixed' '<' totalDigits=INT ',' fractionalDigits=INT '>' name=ID ';'
		public Group getGroup_25() { return cGroup_25; }
		
		//{FixedPtType}
		public Action getFixedPtTypeAction_25_0() { return cFixedPtTypeAction_25_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_25_1() { return cTypedefKeyword_25_1; }
		
		//'fixed'
		public Keyword getFixedKeyword_25_2() { return cFixedKeyword_25_2; }
		
		//'<'
		public Keyword getLessThanSignKeyword_25_3() { return cLessThanSignKeyword_25_3; }
		
		//totalDigits=INT
		public Assignment getTotalDigitsAssignment_25_4() { return cTotalDigitsAssignment_25_4; }
		
		//INT
		public RuleCall getTotalDigitsINTTerminalRuleCall_25_4_0() { return cTotalDigitsINTTerminalRuleCall_25_4_0; }
		
		//','
		public Keyword getCommaKeyword_25_5() { return cCommaKeyword_25_5; }
		
		//fractionalDigits=INT
		public Assignment getFractionalDigitsAssignment_25_6() { return cFractionalDigitsAssignment_25_6; }
		
		//INT
		public RuleCall getFractionalDigitsINTTerminalRuleCall_25_6_0() { return cFractionalDigitsINTTerminalRuleCall_25_6_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_25_7() { return cGreaterThanSignKeyword_25_7; }
		
		//name=ID
		public Assignment getNameAssignment_25_8() { return cNameAssignment_25_8; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_25_8_0() { return cNameIDTerminalRuleCall_25_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_25_9() { return cSemicolonKeyword_25_9; }
	}
	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Member");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cTypeNamedDefinitionCrossReference_0_0 = (CrossReference)cTypeAssignment_0.eContents().get(0);
		private final RuleCall cTypeNamedDefinitionScopedNameParserRuleCall_0_0_1 = (RuleCall)cTypeNamedDefinitionCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		///*
		// * (21) <type_spec> ::= <simple_type_spec>
		// * (22) <simple_type_spec> ::= <base_type_spec>
		// *                         | <scoped_name>
		// * (47) <member> ::= <type_spec> <declarators> ";"
		// * (62) <simple_declarator> ::= <identifier>
		// * (67) <declarators> ::= <declarator> { "," <declarator> }*
		// * (68) <declarator> ::= <simple_declarator>
		// */ Member:
		//	type=[NamedDefinition|ScopedName] name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//type=[NamedDefinition|ScopedName] name=ID ';'
		public Group getGroup() { return cGroup; }
		
		//type=[NamedDefinition|ScopedName]
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//[NamedDefinition|ScopedName]
		public CrossReference getTypeNamedDefinitionCrossReference_0_0() { return cTypeNamedDefinitionCrossReference_0_0; }
		
		//ScopedName
		public RuleCall getTypeNamedDefinitionScopedNameParserRuleCall_0_0_1() { return cTypeNamedDefinitionScopedNameParserRuleCall_0_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class CaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Case");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cCaseKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cLabelsAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cLabelsINTTerminalRuleCall_0_1_0 = (RuleCall)cLabelsAssignment_0_1.eContents().get(0);
		private final Keyword cColonKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeNamedDefinitionCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeNamedDefinitionScopedNameParserRuleCall_1_0_1 = (RuleCall)cTypeNamedDefinitionCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		///*
		// * (21) <type_spec> ::= <simple_type_spec>
		// * (22) <simple_type_spec> ::= <base_type_spec>
		// *                         | <scoped_name>
		// * (53) <case> ::= <case_label>+ <element_spec> ";"
		// * (54) <case_label> ::= "case" <const_expr> ":"
		// *                   | "default" ":"
		// * (55) <element_spec> ::= <type_spec> <declarator>
		// * (62) <simple_declarator> ::= <identifier>
		// * (68) <declarator> ::= <simple_declarator>
		// */ Case:
		//	('case' labels+=INT ':')+ type=[NamedDefinition|ScopedName] name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//('case' labels+=INT ':')+ type=[NamedDefinition|ScopedName] name=ID ';'
		public Group getGroup() { return cGroup; }
		
		//('case' labels+=INT ':')+
		public Group getGroup_0() { return cGroup_0; }
		
		//'case'
		public Keyword getCaseKeyword_0_0() { return cCaseKeyword_0_0; }
		
		//labels+=INT
		public Assignment getLabelsAssignment_0_1() { return cLabelsAssignment_0_1; }
		
		//INT
		public RuleCall getLabelsINTTerminalRuleCall_0_1_0() { return cLabelsINTTerminalRuleCall_0_1_0; }
		
		//':'
		public Keyword getColonKeyword_0_2() { return cColonKeyword_0_2; }
		
		//type=[NamedDefinition|ScopedName]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[NamedDefinition|ScopedName]
		public CrossReference getTypeNamedDefinitionCrossReference_1_0() { return cTypeNamedDefinitionCrossReference_1_0; }
		
		//ScopedName
		public RuleCall getTypeNamedDefinitionScopedNameParserRuleCall_1_0_1() { return cTypeNamedDefinitionScopedNameParserRuleCall_1_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class ScopedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.ScopedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cColonColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		///*
		// * (4) <scoped_name> ::= <identifier>
		// *                   | "::" <identifier>
		// *                   | <scoped_name> "::" <identifier>
		// */ ScopedName:
		//	'::'? (ID '::')* ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'::'? (ID '::')* ID
		public Group getGroup() { return cGroup; }
		
		//'::'?
		public Keyword getColonColonKeyword_0() { return cColonColonKeyword_0; }
		
		//(ID '::')*
		public Group getGroup_1() { return cGroup_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_0() { return cIDTerminalRuleCall_1_0; }
		
		//'::'
		public Keyword getColonColonKeyword_1_1() { return cColonColonKeyword_1_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2() { return cIDTerminalRuleCall_2; }
	}
	
	
	private final SpecificationElements pSpecification;
	private final DefinitionElements pDefinition;
	private final NamedDefinitionElements pNamedDefinition;
	private final MemberElements pMember;
	private final CaseElements pCase;
	private final ScopedNameElements pScopedName;
	private final TerminalRule tID;
	private final TerminalRule tPREPROCESSOR;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SimpleIDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSpecification = new SpecificationElements();
		this.pDefinition = new DefinitionElements();
		this.pNamedDefinition = new NamedDefinitionElements();
		this.pMember = new MemberElements();
		this.pCase = new CaseElements();
		this.pScopedName = new ScopedNameElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.ID");
		this.tPREPROCESSOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.PREPROCESSOR");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.osate.simpleidl.SimpleIDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*
	// * This is a subset of IDL 4.2. It is intended to be used to parse IDL files generated from the FACE Conformance Test
	// * Suite 3.0. Portions of IDL which are not generated by the FACE CTS are not included in this subset.
	// * 
	// * In one case, FACE's version of IDL in the FACE standard disagrees with the IDL standard. In FACE, a union has an
	// * opening curly between the union's name and the "switch" keyword. It also has a corresponding closing curly and
	// * semicolon at the end of the union. These are not in the IDL standard. This subset follows the FACE standard for
	// * unions and deviates from the IDL standard.
	// * 
	// * The comments on each grammar rule in this file contain the relevant syntax definitions from the IDL standard's
	// * Annex A: Consolidated IDL Grammar.
	// */ /*
	// * (1) <specification> ::= <definition>+
	// */ Specification:
	//	definitions+=Definition+;
	public SpecificationElements getSpecificationAccess() {
		return pSpecification;
	}
	
	public ParserRule getSpecificationRule() {
		return getSpecificationAccess().getRule();
	}
	
	///*
	// * (2) <definition> ::= <module_dcl> ";"
	// *                  | <const_dcl> ";"
	// *                  | <type_dcl> ";"
	// * (20) <type_dcl> ::= <constr_type_dcl>
	// *                 | <native_dcl>
	// *                 | <typedef_dcl>
	// * (44) <constr_type_dcl> ::= <struct_dcl>
	// *                        | <union_dcl>
	// *                        | <enum_dcl>
	// * (45) <struct_dcl> ::= <struct_def>
	// *                   | <struct_forward_dcl>
	// * (48) <struct_forward_dcl> ::= "struct" <identifier>
	// */ Definition:
	//	NamedDefinition | {StructForward} 'struct' struct=[Struct] ';';
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}
	
	///*
	// * (2) <definition> ::= <module_dcl> ";"
	// *                  | <const_dcl> ";"
	// *                  | <type_dcl> ";"
	// * (3) <module_dcl> ::= "module" <identifier> "{" <definition>+ "}"
	// * (20) <type_dcl> ::= <constr_type_dcl>
	// *                 | <native_dcl>
	// *                 | <typedef_dcl>
	// * (21) <type_spec> ::= <simple_type_spec>
	// * (22) <simple_type_spec> ::= <base_type_spec>
	// *                         | <scoped_name>
	// * (23) <base_type_spec> ::= <integer_type>
	// *                       | <floating_pt_type>
	// *                       | <char_type>
	// *                       | <wide_char_type>
	// *                       | <boolean_type>
	// *                       | <octet_type>
	// * (24) <floating_pt_type> ::= "float"
	// *                         | "double"
	// *                         | "long" "double"
	// * (25) <integer_type> ::= <signed_int>
	// *                     | <unsigned_int>
	// * (26) <signed_int> ::= <signed_short_int>
	// *                   | <signed_long_int>
	// *                   | <signed_longlong_int>
	// * (27) <signed_short_int> ::= "short"
	// * (28) <signed_long_int> ::= "long"
	// * (29) <signed_longlong_int> ::= "long" "long"
	// * (30) <unsigned_int> ::= <unsigned_short_int>
	// *                     | <unsigned_long_int>
	// *                     | <unsigned_longlong_int>
	// * (31) <unsigned_short_int> ::= "unsigned" "short"
	// * (32) <unsigned_long_int> ::= "unsigned" "long"
	// * (33) <unsigned_longlong_int> ::= "unsigned" "long" "long"
	// * (34) <char_type> ::= "char"
	// * (35) <wide_char_type> ::= "wchar"
	// * (36) <boolean_type> ::= "boolean"
	// * (37) <octet_type> ::= "octet"
	// * (38) <template_type_spec> ::= <sequence_type>
	// *                           | <string_type>
	// *                           | <wide_string_type>
	// *                           | <fixed_pt_type>
	// * (39) <sequence_type> ::= "sequence" "<" <type_spec> "," <positive_int_const> ">"
	// *                      | "sequence" "<" <type_spec> ">"
	// * (40) <string_type> ::= "string" "<" <positive_int_const> ">"
	// *                    | "string"
	// * (41) <wide_string_type> ::= "wstring" "<" <positive_int_const> ">"
	// *                         | "wstring"
	// * (42) <fixed_pt_type> ::= "fixed" "<" <positive_int_const> "," <positive_int_const> ">"
	// * (44) <constr_type_dcl> ::= <struct_dcl>
	// *                        | <union_dcl>
	// *                        | <enum_dcl>
	// * (45) <struct_dcl> ::= <struct_def>
	// *                   | <struct_forward_dcl>
	// * (46) <struct_def> ::= "struct" <identifier> "{" <member>+ "}"
	// * (49) <union_dcl> ::= <union_def>
	// *                  | <union_forward_dcl>
	// * (50) <union_def> ::= "union" <identifier> "switch" "(" <switch_type_spec> ")"
	// *                      "{" <switch_body> "}"
	// * (51) <switch_type_spec> ::= <integer_type>
	// *                         | <char_type>
	// *                         | <boolean_type>
	// *                         | <scoped_name>
	// * (52) <switch_body> ::= <case>+
	// * (57) <enum_dcl> ::= "enum" <identifier>
	// *                     "{" <enumerator> { "," <enumerator> } * "}"
	// * (58) <enumerator> ::= <identifier>
	// * (59) <array_declarator> ::= <identifier> <fixed_array_size>+
	// * (60) <fixed_array_size> ::= "[" <positive_int_const> "]"
	// * (62) <simple_declarator> ::= <identifier>
	// * (63) <typedef_dcl> ::= "typedef" <type_declarator>
	// * (64) <type_declarator> ::= { <simple_type_spec>
	// *                            | <template_type_spec>
	// *                            | <constr_type_dcl>
	// *                            } <any_declarators>
	// * (65) <any_declarators> ::= <any_declarator> { "," <any_declarator> }*
	// * (66) <any_declarator> ::= <simple_declarator>
	// *                       | <array_declarator>
	// */ NamedDefinition:
	//	{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';' | {Struct} 'struct' name=ID '{' members+=Member+ '}'
	//	';' | {Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')' '{' cases+=Case+ '}' ';' '}' ';' | {Enum} 'enum'
	//	name=ID '{' literals+=ID (',' literals+=ID)* '}' ';' | {ArrayType} 'typedef' type=[NamedDefinition|ScopedName] name=ID
	//	'[' size=INT ']' ';' | {SignedShortInt} 'typedef' 'short' name=ID ';' | {SignedLongInt} 'typedef' 'long' name=ID ';' |
	//	{SignedLongLongInt} 'typedef' 'long' 'long' name=ID ';' | {UnsignedShortInt} 'typedef' 'unsigned' 'short' name=ID ';'
	//	| {UnsignedLongInt} 'typedef' 'unsigned' 'long' name=ID ';' | {UnsignedLongLongInt} 'typedef' 'unsigned' 'long' 'long'
	//	name=ID ';' | {FloatType} 'typedef' 'float' name=ID ';' | {DoubleType} 'typedef' 'double' name=ID ';' |
	//	{LongDoubleType} 'typedef' 'long' 'double' name=ID ';' | {CharType} 'typedef' 'char' name=ID ';' | {WideCharType}
	//	'typedef' 'wchar' name=ID ';' | {BooleanType} 'typedef' 'boolean' name=ID ';' | {OctetType} 'typedef' 'octet' name=ID
	//	';' | {ReferencedType} 'typedef' type=[NamedDefinition|ScopedName] name=ID ';' | {BoundedSequence} 'typedef'
	//	'sequence' '<' type=[NamedDefinition|ScopedName] ',' size=INT '>' name=ID ';' | {UnboundedSequence} 'typedef'
	//	'sequence' '<' type=[NamedDefinition|ScopedName] '>' name=ID ';' | {BoundedString} 'typedef' 'string' '<' size=INT '>'
	//	name=ID ';' | {UnboundedString} 'typedef' 'string' name=ID ';' | {BoundedWideString} 'typedef' 'wstring' '<' size=INT
	//	'>' name=ID ';' | {UnboundedWideString} 'typedef' 'wstring' name=ID ';' | {FixedPtType} 'typedef' 'fixed' '<'
	//	totalDigits=INT ',' fractionalDigits=INT '>' name=ID ';';
	public NamedDefinitionElements getNamedDefinitionAccess() {
		return pNamedDefinition;
	}
	
	public ParserRule getNamedDefinitionRule() {
		return getNamedDefinitionAccess().getRule();
	}
	
	///*
	// * (21) <type_spec> ::= <simple_type_spec>
	// * (22) <simple_type_spec> ::= <base_type_spec>
	// *                         | <scoped_name>
	// * (47) <member> ::= <type_spec> <declarators> ";"
	// * (62) <simple_declarator> ::= <identifier>
	// * (67) <declarators> ::= <declarator> { "," <declarator> }*
	// * (68) <declarator> ::= <simple_declarator>
	// */ Member:
	//	type=[NamedDefinition|ScopedName] name=ID ';';
	public MemberElements getMemberAccess() {
		return pMember;
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}
	
	///*
	// * (21) <type_spec> ::= <simple_type_spec>
	// * (22) <simple_type_spec> ::= <base_type_spec>
	// *                         | <scoped_name>
	// * (53) <case> ::= <case_label>+ <element_spec> ";"
	// * (54) <case_label> ::= "case" <const_expr> ":"
	// *                   | "default" ":"
	// * (55) <element_spec> ::= <type_spec> <declarator>
	// * (62) <simple_declarator> ::= <identifier>
	// * (68) <declarator> ::= <simple_declarator>
	// */ Case:
	//	('case' labels+=INT ':')+ type=[NamedDefinition|ScopedName] name=ID ';';
	public CaseElements getCaseAccess() {
		return pCase;
	}
	
	public ParserRule getCaseRule() {
		return getCaseAccess().getRule();
	}
	
	///*
	// * (4) <scoped_name> ::= <identifier>
	// *                   | "::" <identifier>
	// *                   | <scoped_name> "::" <identifier>
	// */ ScopedName:
	//	'::'? (ID '::')* ID;
	public ScopedNameElements getScopedNameAccess() {
		return pScopedName;
	}
	
	public ParserRule getScopedNameRule() {
		return getScopedNameAccess().getRule();
	}
	
	//@Override
	//terminal ID:
	//	('a'..'z' | 'A'..'Z') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal PREPROCESSOR:
	//	('#define' | '#endif' | '#ifndef' | '#include') !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getPREPROCESSORRule() {
		return tPREPROCESSOR;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
