/*******************************************************************************
 * FACE Data Model to AADL Translator
 * 
 * Copyright 2018 Carnegie Mellon University. All Rights Reserved.
 * 
 * NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON
 * AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
 * AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY,
 * EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY
 * WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 * 
 * Released under an Eclipse Public License - v1.0-style license, please see license.txt or contact
 * permission@sei.cmu.edu for full terms.
 * 
 * [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.
 * Please see Copyright notice for non-US Government use and distribution.
 * 
 * DM18-0762
 *******************************************************************************/
package org.osate.simpleidl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SimpleIDLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Specification");
		private final Assignment cDefinitionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDefinitionsDefinitionParserRuleCall_0 = (RuleCall)cDefinitionsAssignment.eContents().get(0);
		
		///*
		// * This is a subset of IDL 4.2. It is intended to be used to parse IDL files generated from the FACE Conformance Test
		// * Suite 3.0. Portions of IDL which are not generated by the FACE CTS are not included in this subset.
		// * 
		// * In one case, FACE's version of IDL in the FACE standard disagrees with the IDL standard. In FACE, a union has an
		// * opening curly between the union's name and the "switch" keyword. It also has a corresponding closing curly and
		// * semicolon at the end of the union. These are not in the IDL standard. This subset follows the FACE standard for
		// * unions and deviates from the IDL standard.
		// * 
		// * The comments on each grammar rule in this file contain the relevant syntax definitions from the IDL standard's
		// * Annex A: Consolidated IDL Grammar.
		// */ /*
		// * (1) <specification> ::= <definition>+
		// */ Specification:
		//	definitions+=Definition+;
		@Override public ParserRule getRule() { return rule; }
		
		//definitions+=Definition+
		public Assignment getDefinitionsAssignment() { return cDefinitionsAssignment; }
		
		//Definition
		public RuleCall getDefinitionsDefinitionParserRuleCall_0() { return cDefinitionsDefinitionParserRuleCall_0; }
	}
	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Definition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cModuleAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cModuleKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cDefinitionsAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cDefinitionsDefinitionParserRuleCall_0_4_0 = (RuleCall)cDefinitionsAssignment_0_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_0_5 = (Keyword)cGroup_0.eContents().get(5);
		private final Keyword cSemicolonKeyword_0_6 = (Keyword)cGroup_0.eContents().get(6);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cStructAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cStructKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cNameAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_1_2_0 = (RuleCall)cNameAssignment_1_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cMembersAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cMembersMemberParserRuleCall_1_4_0 = (RuleCall)cMembersAssignment_1_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		private final Keyword cSemicolonKeyword_1_6 = (Keyword)cGroup_1.eContents().get(6);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cStructForwardAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cStructKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cStructAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final CrossReference cStructStructCrossReference_2_2_0 = (CrossReference)cStructAssignment_2_2.eContents().get(0);
		private final RuleCall cStructStructIDTerminalRuleCall_2_2_0_1 = (RuleCall)cStructStructCrossReference_2_2_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cUnionAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cUnionKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cNameAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_3_2_0 = (RuleCall)cNameAssignment_3_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Keyword cSwitchKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_3_5 = (Keyword)cGroup_3.eContents().get(5);
		private final Keyword cUnsignedKeyword_3_6 = (Keyword)cGroup_3.eContents().get(6);
		private final Keyword cShortKeyword_3_7 = (Keyword)cGroup_3.eContents().get(7);
		private final Keyword cRightParenthesisKeyword_3_8 = (Keyword)cGroup_3.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_3_9 = (Keyword)cGroup_3.eContents().get(9);
		private final Assignment cCasesAssignment_3_10 = (Assignment)cGroup_3.eContents().get(10);
		private final RuleCall cCasesCaseParserRuleCall_3_10_0 = (RuleCall)cCasesAssignment_3_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_11 = (Keyword)cGroup_3.eContents().get(11);
		private final Keyword cSemicolonKeyword_3_12 = (Keyword)cGroup_3.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_3_13 = (Keyword)cGroup_3.eContents().get(13);
		private final Keyword cSemicolonKeyword_3_14 = (Keyword)cGroup_3.eContents().get(14);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cEnumAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cEnumKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cNameAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_4_2_0 = (RuleCall)cNameAssignment_4_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Assignment cLiteralsAssignment_4_4 = (Assignment)cGroup_4.eContents().get(4);
		private final RuleCall cLiteralsIDTerminalRuleCall_4_4_0 = (RuleCall)cLiteralsAssignment_4_4.eContents().get(0);
		private final Group cGroup_4_5 = (Group)cGroup_4.eContents().get(5);
		private final Keyword cCommaKeyword_4_5_0 = (Keyword)cGroup_4_5.eContents().get(0);
		private final Assignment cLiteralsAssignment_4_5_1 = (Assignment)cGroup_4_5.eContents().get(1);
		private final RuleCall cLiteralsIDTerminalRuleCall_4_5_1_0 = (RuleCall)cLiteralsAssignment_4_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_6 = (Keyword)cGroup_4.eContents().get(6);
		private final Keyword cSemicolonKeyword_4_7 = (Keyword)cGroup_4.eContents().get(7);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cTypedefAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cTypedefKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cTypeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cTypeTypeParserRuleCall_5_2_0 = (RuleCall)cTypeAssignment_5_2.eContents().get(0);
		private final Assignment cNameAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_5_3_0 = (RuleCall)cNameAssignment_5_3.eContents().get(0);
		private final Assignment cArraySizeAssignment_5_4 = (Assignment)cGroup_5.eContents().get(4);
		private final RuleCall cArraySizeFixedArraySizeParserRuleCall_5_4_0 = (RuleCall)cArraySizeAssignment_5_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		
		///*
		// * (2) <definition> ::= <module_dcl> ";"
		// *                  | <const_dcl> ";"
		// *                  | <type_dcl> ";"
		// * (3) <module_dcl> ::= "module" <identifier> "{" <definition>+ "}"
		// * (20) <type_dcl> ::= <constr_type_dcl>
		// *                 | <native_dcl>
		// *                 | <typedef_dcl>
		// * (44) <constr_type_dcl> ::= <struct_dcl>
		// *                        | <union_dcl>
		// *                        | <enum_dcl>
		// * (45) <struct_dcl> ::= <struct_def>
		// *                   | <struct_forward_dcl>
		// * (46) <struct_def> ::= "struct" <identifier> "{" <member>+ "}"
		// * (48) <struct_forward_dcl> ::= "struct" <identifier>
		// * (49) <union_dcl> ::= <union_def>
		// *                  | <union_forward_dcl>
		// * (50) <union_def> ::= "union" <identifier> "switch" "(" <switch_type_spec> ")"
		// *                      "{" <switch_body> "}"
		// * (51) <switch_type_spec> ::= <integer_type>
		// *                         | <char_type>
		// *                         | <boolean_type>
		// *                         | <scoped_name>
		// * (52) <switch_body> ::= <case>+
		// * (57) <enum_dcl> ::= "enum" <identifier>
		// *                     "{" <enumerator> { "," <enumerator> } * "}"
		// * (58) <enumerator> ::= <identifier>
		// * (59) <array_declarator> ::= <identifier> <fixed_array_size>+
		// * (62) <simple_declarator> ::= <identifier>
		// * (63) <typedef_dcl> ::= "typedef" <type_declarator>
		// * (64) <type_declarator> ::= { <simple_type_spec>
		// *                            | <template_type_spec>
		// *                            | <constr_type_dcl>
		// *                            } <any_declarators>
		// * (65) <any_declarators> ::= <any_declarator> { "," <any_declarator> }*
		// * (66) <any_declarator> ::= <simple_declarator>
		// *                       | <array_declarator>
		// */ Definition:
		//	{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';' | {Struct} 'struct' name=ID '{' members+=Member+ '}'
		//	';' | {StructForward} 'struct' struct=[Struct] ';' | {Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')'
		//	'{' cases+=Case+ '}' ';' '}' ';' | {Enum} 'enum' name=ID '{' literals+=ID (',' literals+=ID)* '}' ';' | {Typedef}
		//	'typedef' type=Type name=ID arraySize=FixedArraySize? ';';
		@Override public ParserRule getRule() { return rule; }
		
		//{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';' | {Struct} 'struct' name=ID '{' members+=Member+ '}' ';'
		//| {StructForward} 'struct' struct=[Struct] ';' | {Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')' '{'
		//cases+=Case+ '}' ';' '}' ';' | {Enum} 'enum' name=ID '{' literals+=ID (',' literals+=ID)* '}' ';' | {Typedef} 'typedef'
		//type=Type name=ID arraySize=FixedArraySize? ';'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';'
		public Group getGroup_0() { return cGroup_0; }
		
		//{Module}
		public Action getModuleAction_0_0() { return cModuleAction_0_0; }
		
		//'module'
		public Keyword getModuleKeyword_0_1() { return cModuleKeyword_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0_3() { return cLeftCurlyBracketKeyword_0_3; }
		
		//definitions+=Definition+
		public Assignment getDefinitionsAssignment_0_4() { return cDefinitionsAssignment_0_4; }
		
		//Definition
		public RuleCall getDefinitionsDefinitionParserRuleCall_0_4_0() { return cDefinitionsDefinitionParserRuleCall_0_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_0_5() { return cRightCurlyBracketKeyword_0_5; }
		
		//';'
		public Keyword getSemicolonKeyword_0_6() { return cSemicolonKeyword_0_6; }
		
		//{Struct} 'struct' name=ID '{' members+=Member+ '}' ';'
		public Group getGroup_1() { return cGroup_1; }
		
		//{Struct}
		public Action getStructAction_1_0() { return cStructAction_1_0; }
		
		//'struct'
		public Keyword getStructKeyword_1_1() { return cStructKeyword_1_1; }
		
		//name=ID
		public Assignment getNameAssignment_1_2() { return cNameAssignment_1_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_2_0() { return cNameIDTerminalRuleCall_1_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_3() { return cLeftCurlyBracketKeyword_1_3; }
		
		//members+=Member+
		public Assignment getMembersAssignment_1_4() { return cMembersAssignment_1_4; }
		
		//Member
		public RuleCall getMembersMemberParserRuleCall_1_4_0() { return cMembersMemberParserRuleCall_1_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_5() { return cRightCurlyBracketKeyword_1_5; }
		
		//';'
		public Keyword getSemicolonKeyword_1_6() { return cSemicolonKeyword_1_6; }
		
		//{StructForward} 'struct' struct=[Struct] ';'
		public Group getGroup_2() { return cGroup_2; }
		
		//{StructForward}
		public Action getStructForwardAction_2_0() { return cStructForwardAction_2_0; }
		
		//'struct'
		public Keyword getStructKeyword_2_1() { return cStructKeyword_2_1; }
		
		//struct=[Struct]
		public Assignment getStructAssignment_2_2() { return cStructAssignment_2_2; }
		
		//[Struct]
		public CrossReference getStructStructCrossReference_2_2_0() { return cStructStructCrossReference_2_2_0; }
		
		//ID
		public RuleCall getStructStructIDTerminalRuleCall_2_2_0_1() { return cStructStructIDTerminalRuleCall_2_2_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_2_3() { return cSemicolonKeyword_2_3; }
		
		//{Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')' '{' cases+=Case+ '}' ';' '}' ';'
		public Group getGroup_3() { return cGroup_3; }
		
		//{Union}
		public Action getUnionAction_3_0() { return cUnionAction_3_0; }
		
		//'union'
		public Keyword getUnionKeyword_3_1() { return cUnionKeyword_3_1; }
		
		//name=ID
		public Assignment getNameAssignment_3_2() { return cNameAssignment_3_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_2_0() { return cNameIDTerminalRuleCall_3_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_3() { return cLeftCurlyBracketKeyword_3_3; }
		
		//'switch'
		public Keyword getSwitchKeyword_3_4() { return cSwitchKeyword_3_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_5() { return cLeftParenthesisKeyword_3_5; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_3_6() { return cUnsignedKeyword_3_6; }
		
		//'short'
		public Keyword getShortKeyword_3_7() { return cShortKeyword_3_7; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_8() { return cRightParenthesisKeyword_3_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_9() { return cLeftCurlyBracketKeyword_3_9; }
		
		//cases+=Case+
		public Assignment getCasesAssignment_3_10() { return cCasesAssignment_3_10; }
		
		//Case
		public RuleCall getCasesCaseParserRuleCall_3_10_0() { return cCasesCaseParserRuleCall_3_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_11() { return cRightCurlyBracketKeyword_3_11; }
		
		//';'
		public Keyword getSemicolonKeyword_3_12() { return cSemicolonKeyword_3_12; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_13() { return cRightCurlyBracketKeyword_3_13; }
		
		//';'
		public Keyword getSemicolonKeyword_3_14() { return cSemicolonKeyword_3_14; }
		
		//{Enum} 'enum' name=ID '{' literals+=ID (',' literals+=ID)* '}' ';'
		public Group getGroup_4() { return cGroup_4; }
		
		//{Enum}
		public Action getEnumAction_4_0() { return cEnumAction_4_0; }
		
		//'enum'
		public Keyword getEnumKeyword_4_1() { return cEnumKeyword_4_1; }
		
		//name=ID
		public Assignment getNameAssignment_4_2() { return cNameAssignment_4_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_2_0() { return cNameIDTerminalRuleCall_4_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_3() { return cLeftCurlyBracketKeyword_4_3; }
		
		//literals+=ID
		public Assignment getLiteralsAssignment_4_4() { return cLiteralsAssignment_4_4; }
		
		//ID
		public RuleCall getLiteralsIDTerminalRuleCall_4_4_0() { return cLiteralsIDTerminalRuleCall_4_4_0; }
		
		//(',' literals+=ID)*
		public Group getGroup_4_5() { return cGroup_4_5; }
		
		//','
		public Keyword getCommaKeyword_4_5_0() { return cCommaKeyword_4_5_0; }
		
		//literals+=ID
		public Assignment getLiteralsAssignment_4_5_1() { return cLiteralsAssignment_4_5_1; }
		
		//ID
		public RuleCall getLiteralsIDTerminalRuleCall_4_5_1_0() { return cLiteralsIDTerminalRuleCall_4_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_6() { return cRightCurlyBracketKeyword_4_6; }
		
		//';'
		public Keyword getSemicolonKeyword_4_7() { return cSemicolonKeyword_4_7; }
		
		//{Typedef} 'typedef' type=Type name=ID arraySize=FixedArraySize? ';'
		public Group getGroup_5() { return cGroup_5; }
		
		//{Typedef}
		public Action getTypedefAction_5_0() { return cTypedefAction_5_0; }
		
		//'typedef'
		public Keyword getTypedefKeyword_5_1() { return cTypedefKeyword_5_1; }
		
		//type=Type
		public Assignment getTypeAssignment_5_2() { return cTypeAssignment_5_2; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_5_2_0() { return cTypeTypeParserRuleCall_5_2_0; }
		
		//name=ID
		public Assignment getNameAssignment_5_3() { return cNameAssignment_5_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_5_3_0() { return cNameIDTerminalRuleCall_5_3_0; }
		
		//arraySize=FixedArraySize?
		public Assignment getArraySizeAssignment_5_4() { return cArraySizeAssignment_5_4; }
		
		//FixedArraySize
		public RuleCall getArraySizeFixedArraySizeParserRuleCall_5_4_0() { return cArraySizeFixedArraySizeParserRuleCall_5_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_5() { return cSemicolonKeyword_5_5; }
	}
	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Member");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeSimpleTypeSpecParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		///*
		// * (21) <type_spec> ::= <simple_type_spec>
		// * (47) <member> ::= <type_spec> <declarators> ";"
		// * (62) <simple_declarator> ::= <identifier>
		// * (67) <declarators> ::= <declarator> { "," <declarator> }*
		// * (68) <declarator> ::= <simple_declarator>
		// */ Member:
		//	type=SimpleTypeSpec name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//type=SimpleTypeSpec name=ID ';'
		public Group getGroup() { return cGroup; }
		
		//type=SimpleTypeSpec
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//SimpleTypeSpec
		public RuleCall getTypeSimpleTypeSpecParserRuleCall_0_0() { return cTypeSimpleTypeSpecParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class CaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Case");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cCaseKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cLabelsAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cLabelsINTTerminalRuleCall_0_1_0 = (RuleCall)cLabelsAssignment_0_1.eContents().get(0);
		private final Keyword cColonKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeSimpleTypeSpecParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		///*
		// * (21) <type_spec> ::= <simple_type_spec>
		// * (53) <case> ::= <case_label>+ <element_spec> ";"
		// * (54) <case_label> ::= "case" <const_expr> ":"
		// *                   | "default" ":"
		// * (55) <element_spec> ::= <type_spec> <declarator>
		// * (62) <simple_declarator> ::= <identifier>
		// * (68) <declarator> ::= <simple_declarator>
		// */ Case:
		//	('case' labels+=INT ':')+ type=SimpleTypeSpec name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//('case' labels+=INT ':')+ type=SimpleTypeSpec name=ID ';'
		public Group getGroup() { return cGroup; }
		
		//('case' labels+=INT ':')+
		public Group getGroup_0() { return cGroup_0; }
		
		//'case'
		public Keyword getCaseKeyword_0_0() { return cCaseKeyword_0_0; }
		
		//labels+=INT
		public Assignment getLabelsAssignment_0_1() { return cLabelsAssignment_0_1; }
		
		//INT
		public RuleCall getLabelsINTTerminalRuleCall_0_1_0() { return cLabelsINTTerminalRuleCall_0_1_0; }
		
		//':'
		public Keyword getColonKeyword_0_2() { return cColonKeyword_0_2; }
		
		//type=SimpleTypeSpec
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//SimpleTypeSpec
		public RuleCall getTypeSimpleTypeSpecParserRuleCall_1_0() { return cTypeSimpleTypeSpecParserRuleCall_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class FixedArraySizeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.FixedArraySize");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSizeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSizeINTTerminalRuleCall_1_0 = (RuleCall)cSizeAssignment_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		///*
		// * (60) <fixed_array_size> ::= "[" <positive_int_const> "]"
		// */ FixedArraySize:
		//	'[' size=INT ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'[' size=INT ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//size=INT
		public Assignment getSizeAssignment_1() { return cSizeAssignment_1; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_1_0() { return cSizeINTTerminalRuleCall_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSimpleTypeSpecParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cBoundedSequenceAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cSequenceKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Keyword cLessThanSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cTypeAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cTypeSimpleTypeSpecParserRuleCall_1_3_0 = (RuleCall)cTypeAssignment_1_3.eContents().get(0);
		private final Keyword cCommaKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		private final Assignment cSizeAssignment_1_5 = (Assignment)cGroup_1.eContents().get(5);
		private final RuleCall cSizeINTTerminalRuleCall_1_5_0 = (RuleCall)cSizeAssignment_1_5.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1_6 = (Keyword)cGroup_1.eContents().get(6);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cUnboundedSequenceAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cSequenceKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Keyword cLessThanSignKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cTypeAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cTypeSimpleTypeSpecParserRuleCall_2_3_0 = (RuleCall)cTypeAssignment_2_3.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cBoundedStringAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cStringKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cLessThanSignKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cSizeAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cSizeINTTerminalRuleCall_3_3_0 = (RuleCall)cSizeAssignment_3_3.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cUnboundedStringAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cStringKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cBoundedWideStringAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cWstringKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLessThanSignKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cSizeAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cSizeINTTerminalRuleCall_5_3_0 = (RuleCall)cSizeAssignment_5_3.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cUnboundedWideStringAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Keyword cWstringKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Group cGroup_7 = (Group)cAlternatives.eContents().get(7);
		private final Action cFixedPtTypeAction_7_0 = (Action)cGroup_7.eContents().get(0);
		private final Keyword cFixedKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Keyword cLessThanSignKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Assignment cTotalDigitsAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cTotalDigitsINTTerminalRuleCall_7_3_0 = (RuleCall)cTotalDigitsAssignment_7_3.eContents().get(0);
		private final Keyword cCommaKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Assignment cFractionalDigitsAssignment_7_5 = (Assignment)cGroup_7.eContents().get(5);
		private final RuleCall cFractionalDigitsINTTerminalRuleCall_7_5_0 = (RuleCall)cFractionalDigitsAssignment_7_5.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_7_6 = (Keyword)cGroup_7.eContents().get(6);
		
		///*
		// * (21) <type_spec> ::= <simple_type_spec>
		// * (38) <template_type_spec> ::= <sequence_type>
		// *                           | <string_type>
		// *                           | <wide_string_type>
		// *                           | <fixed_pt_type>
		// * (39) <sequence_type> ::= "sequence" "<" <type_spec> "," <positive_int_const> ">"
		// *                      | "sequence" "<" <type_spec> ">"
		// * (40) <string_type> ::= "string" "<" <positive_int_const> ">"
		// *                    | "string"
		// * (41) <wide_string_type> ::= "wstring" "<" <positive_int_const> ">"
		// *                         | "wstring"
		// * (42) <fixed_pt_type> ::= "fixed" "<" <positive_int_const> "," <positive_int_const> ">"
		// * (64) <type_declarator> ::= { <simple_type_spec>
		// *                            | <template_type_spec>
		// *                            | <constr_type_dcl>
		// *                            } <any_declarators>
		// */ Type:
		//	SimpleTypeSpec | {BoundedSequence} 'sequence' '<' type=SimpleTypeSpec ',' size=INT '>' | {UnboundedSequence}
		//	'sequence' '<' type=SimpleTypeSpec '>' | {BoundedString} 'string' '<' size=INT '>' | {UnboundedString} 'string' |
		//	{BoundedWideString} 'wstring' '<' size=INT '>' | {UnboundedWideString} 'wstring' | {FixedPtType} 'fixed' '<'
		//	totalDigits=INT ',' fractionalDigits=INT '>';
		@Override public ParserRule getRule() { return rule; }
		
		//SimpleTypeSpec | {BoundedSequence} 'sequence' '<' type=SimpleTypeSpec ',' size=INT '>' | {UnboundedSequence} 'sequence'
		//'<' type=SimpleTypeSpec '>' | {BoundedString} 'string' '<' size=INT '>' | {UnboundedString} 'string' |
		//{BoundedWideString} 'wstring' '<' size=INT '>' | {UnboundedWideString} 'wstring' | {FixedPtType} 'fixed' '<'
		//totalDigits=INT ',' fractionalDigits=INT '>'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SimpleTypeSpec
		public RuleCall getSimpleTypeSpecParserRuleCall_0() { return cSimpleTypeSpecParserRuleCall_0; }
		
		//{BoundedSequence} 'sequence' '<' type=SimpleTypeSpec ',' size=INT '>'
		public Group getGroup_1() { return cGroup_1; }
		
		//{BoundedSequence}
		public Action getBoundedSequenceAction_1_0() { return cBoundedSequenceAction_1_0; }
		
		//'sequence'
		public Keyword getSequenceKeyword_1_1() { return cSequenceKeyword_1_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_1_2() { return cLessThanSignKeyword_1_2; }
		
		//type=SimpleTypeSpec
		public Assignment getTypeAssignment_1_3() { return cTypeAssignment_1_3; }
		
		//SimpleTypeSpec
		public RuleCall getTypeSimpleTypeSpecParserRuleCall_1_3_0() { return cTypeSimpleTypeSpecParserRuleCall_1_3_0; }
		
		//','
		public Keyword getCommaKeyword_1_4() { return cCommaKeyword_1_4; }
		
		//size=INT
		public Assignment getSizeAssignment_1_5() { return cSizeAssignment_1_5; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_1_5_0() { return cSizeINTTerminalRuleCall_1_5_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1_6() { return cGreaterThanSignKeyword_1_6; }
		
		//{UnboundedSequence} 'sequence' '<' type=SimpleTypeSpec '>'
		public Group getGroup_2() { return cGroup_2; }
		
		//{UnboundedSequence}
		public Action getUnboundedSequenceAction_2_0() { return cUnboundedSequenceAction_2_0; }
		
		//'sequence'
		public Keyword getSequenceKeyword_2_1() { return cSequenceKeyword_2_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_2_2() { return cLessThanSignKeyword_2_2; }
		
		//type=SimpleTypeSpec
		public Assignment getTypeAssignment_2_3() { return cTypeAssignment_2_3; }
		
		//SimpleTypeSpec
		public RuleCall getTypeSimpleTypeSpecParserRuleCall_2_3_0() { return cTypeSimpleTypeSpecParserRuleCall_2_3_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_2_4() { return cGreaterThanSignKeyword_2_4; }
		
		//{BoundedString} 'string' '<' size=INT '>'
		public Group getGroup_3() { return cGroup_3; }
		
		//{BoundedString}
		public Action getBoundedStringAction_3_0() { return cBoundedStringAction_3_0; }
		
		//'string'
		public Keyword getStringKeyword_3_1() { return cStringKeyword_3_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_3_2() { return cLessThanSignKeyword_3_2; }
		
		//size=INT
		public Assignment getSizeAssignment_3_3() { return cSizeAssignment_3_3; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_3_3_0() { return cSizeINTTerminalRuleCall_3_3_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_3_4() { return cGreaterThanSignKeyword_3_4; }
		
		//{UnboundedString} 'string'
		public Group getGroup_4() { return cGroup_4; }
		
		//{UnboundedString}
		public Action getUnboundedStringAction_4_0() { return cUnboundedStringAction_4_0; }
		
		//'string'
		public Keyword getStringKeyword_4_1() { return cStringKeyword_4_1; }
		
		//{BoundedWideString} 'wstring' '<' size=INT '>'
		public Group getGroup_5() { return cGroup_5; }
		
		//{BoundedWideString}
		public Action getBoundedWideStringAction_5_0() { return cBoundedWideStringAction_5_0; }
		
		//'wstring'
		public Keyword getWstringKeyword_5_1() { return cWstringKeyword_5_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_5_2() { return cLessThanSignKeyword_5_2; }
		
		//size=INT
		public Assignment getSizeAssignment_5_3() { return cSizeAssignment_5_3; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_5_3_0() { return cSizeINTTerminalRuleCall_5_3_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_5_4() { return cGreaterThanSignKeyword_5_4; }
		
		//{UnboundedWideString} 'wstring'
		public Group getGroup_6() { return cGroup_6; }
		
		//{UnboundedWideString}
		public Action getUnboundedWideStringAction_6_0() { return cUnboundedWideStringAction_6_0; }
		
		//'wstring'
		public Keyword getWstringKeyword_6_1() { return cWstringKeyword_6_1; }
		
		//{FixedPtType} 'fixed' '<' totalDigits=INT ',' fractionalDigits=INT '>'
		public Group getGroup_7() { return cGroup_7; }
		
		//{FixedPtType}
		public Action getFixedPtTypeAction_7_0() { return cFixedPtTypeAction_7_0; }
		
		//'fixed'
		public Keyword getFixedKeyword_7_1() { return cFixedKeyword_7_1; }
		
		//'<'
		public Keyword getLessThanSignKeyword_7_2() { return cLessThanSignKeyword_7_2; }
		
		//totalDigits=INT
		public Assignment getTotalDigitsAssignment_7_3() { return cTotalDigitsAssignment_7_3; }
		
		//INT
		public RuleCall getTotalDigitsINTTerminalRuleCall_7_3_0() { return cTotalDigitsINTTerminalRuleCall_7_3_0; }
		
		//','
		public Keyword getCommaKeyword_7_4() { return cCommaKeyword_7_4; }
		
		//fractionalDigits=INT
		public Assignment getFractionalDigitsAssignment_7_5() { return cFractionalDigitsAssignment_7_5; }
		
		//INT
		public RuleCall getFractionalDigitsINTTerminalRuleCall_7_5_0() { return cFractionalDigitsINTTerminalRuleCall_7_5_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_7_6() { return cGreaterThanSignKeyword_7_6; }
	}
	public class SimpleTypeSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.SimpleTypeSpec");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cSignedShortIntAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cShortKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cSignedLongIntAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cLongKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cSignedLongLongIntAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cLongKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Keyword cLongKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cUnsignedShortIntAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cUnsignedKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Keyword cShortKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cUnsignedLongIntAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cUnsignedKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Keyword cLongKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cUnsignedLongLongIntAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cUnsignedKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLongKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Keyword cLongKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cFloatTypeAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Keyword cFloatKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Group cGroup_7 = (Group)cAlternatives.eContents().get(7);
		private final Action cDoubleTypeAction_7_0 = (Action)cGroup_7.eContents().get(0);
		private final Keyword cDoubleKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Group cGroup_8 = (Group)cAlternatives.eContents().get(8);
		private final Action cLongDoubleTypeAction_8_0 = (Action)cGroup_8.eContents().get(0);
		private final Keyword cLongKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Keyword cDoubleKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		private final Group cGroup_9 = (Group)cAlternatives.eContents().get(9);
		private final Action cCharTypeAction_9_0 = (Action)cGroup_9.eContents().get(0);
		private final Keyword cCharKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Group cGroup_10 = (Group)cAlternatives.eContents().get(10);
		private final Action cWideCharTypeAction_10_0 = (Action)cGroup_10.eContents().get(0);
		private final Keyword cWcharKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Group cGroup_11 = (Group)cAlternatives.eContents().get(11);
		private final Action cBooleanTypeAction_11_0 = (Action)cGroup_11.eContents().get(0);
		private final Keyword cBooleanKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Group cGroup_12 = (Group)cAlternatives.eContents().get(12);
		private final Action cOctetTypeAction_12_0 = (Action)cGroup_12.eContents().get(0);
		private final Keyword cOctetKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Group cGroup_13 = (Group)cAlternatives.eContents().get(13);
		private final Action cReferencedTypeAction_13_0 = (Action)cGroup_13.eContents().get(0);
		private final Assignment cTypeAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final CrossReference cTypeDefinitionCrossReference_13_1_0 = (CrossReference)cTypeAssignment_13_1.eContents().get(0);
		private final RuleCall cTypeDefinitionScopedNameParserRuleCall_13_1_0_1 = (RuleCall)cTypeDefinitionCrossReference_13_1_0.eContents().get(1);
		
		///*
		// * (22) <simple_type_spec> ::= <base_type_spec>
		// *                         | <scoped_name>
		// * (23) <base_type_spec> ::= <integer_type>
		// *                       | <floating_pt_type>
		// *                       | <char_type>
		// *                       | <wide_char_type>
		// *                       | <boolean_type>
		// *                       | <octet_type>
		// * (24) <floating_pt_type> ::= "float"
		// *                         | "double"
		// *                         | "long" "double"
		// * (25) <integer_type> ::= <signed_int>
		// *                     | <unsigned_int>
		// * (26) <signed_int> ::= <signed_short_int>
		// *                   | <signed_long_int>
		// *                   | <signed_longlong_int>
		// * (27) <signed_short_int> ::= "short"
		// * (28) <signed_long_int> ::= "long"
		// * (29) <signed_longlong_int> ::= "long" "long"
		// * (30) <unsigned_int> ::= <unsigned_short_int>
		// *                     | <unsigned_long_int>
		// *                     | <unsigned_longlong_int>
		// * (31) <unsigned_short_int> ::= "unsigned" "short"
		// * (32) <unsigned_long_int> ::= "unsigned" "long"
		// * (33) <unsigned_longlong_int> ::= "unsigned" "long" "long"
		// * (34) <char_type> ::= "char"
		// * (35) <wide_char_type> ::= "wchar"
		// * (36) <boolean_type> ::= "boolean"
		// * (37) <octet_type> ::= "octet"
		// */ SimpleTypeSpec:
		//	{SignedShortInt} 'short' | {SignedLongInt} 'long' | {SignedLongLongInt} 'long' 'long' | {UnsignedShortInt} 'unsigned'
		//	'short' | {UnsignedLongInt} 'unsigned' 'long' | {UnsignedLongLongInt} 'unsigned' 'long' 'long' | {FloatType} 'float' |
		//	{DoubleType} 'double' | {LongDoubleType} 'long' 'double' | {CharType} 'char' | {WideCharType} 'wchar' | {BooleanType}
		//	'boolean' | {OctetType} 'octet' | {ReferencedType} type=[Definition|ScopedName];
		@Override public ParserRule getRule() { return rule; }
		
		//{SignedShortInt} 'short' | {SignedLongInt} 'long' | {SignedLongLongInt} 'long' 'long' | {UnsignedShortInt} 'unsigned'
		//'short' | {UnsignedLongInt} 'unsigned' 'long' | {UnsignedLongLongInt} 'unsigned' 'long' 'long' | {FloatType} 'float' |
		//{DoubleType} 'double' | {LongDoubleType} 'long' 'double' | {CharType} 'char' | {WideCharType} 'wchar' | {BooleanType}
		//'boolean' | {OctetType} 'octet' | {ReferencedType} type=[Definition|ScopedName]
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{SignedShortInt} 'short'
		public Group getGroup_0() { return cGroup_0; }
		
		//{SignedShortInt}
		public Action getSignedShortIntAction_0_0() { return cSignedShortIntAction_0_0; }
		
		//'short'
		public Keyword getShortKeyword_0_1() { return cShortKeyword_0_1; }
		
		//{SignedLongInt} 'long'
		public Group getGroup_1() { return cGroup_1; }
		
		//{SignedLongInt}
		public Action getSignedLongIntAction_1_0() { return cSignedLongIntAction_1_0; }
		
		//'long'
		public Keyword getLongKeyword_1_1() { return cLongKeyword_1_1; }
		
		//{SignedLongLongInt} 'long' 'long'
		public Group getGroup_2() { return cGroup_2; }
		
		//{SignedLongLongInt}
		public Action getSignedLongLongIntAction_2_0() { return cSignedLongLongIntAction_2_0; }
		
		//'long'
		public Keyword getLongKeyword_2_1() { return cLongKeyword_2_1; }
		
		//'long'
		public Keyword getLongKeyword_2_2() { return cLongKeyword_2_2; }
		
		//{UnsignedShortInt} 'unsigned' 'short'
		public Group getGroup_3() { return cGroup_3; }
		
		//{UnsignedShortInt}
		public Action getUnsignedShortIntAction_3_0() { return cUnsignedShortIntAction_3_0; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_3_1() { return cUnsignedKeyword_3_1; }
		
		//'short'
		public Keyword getShortKeyword_3_2() { return cShortKeyword_3_2; }
		
		//{UnsignedLongInt} 'unsigned' 'long'
		public Group getGroup_4() { return cGroup_4; }
		
		//{UnsignedLongInt}
		public Action getUnsignedLongIntAction_4_0() { return cUnsignedLongIntAction_4_0; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_4_1() { return cUnsignedKeyword_4_1; }
		
		//'long'
		public Keyword getLongKeyword_4_2() { return cLongKeyword_4_2; }
		
		//{UnsignedLongLongInt} 'unsigned' 'long' 'long'
		public Group getGroup_5() { return cGroup_5; }
		
		//{UnsignedLongLongInt}
		public Action getUnsignedLongLongIntAction_5_0() { return cUnsignedLongLongIntAction_5_0; }
		
		//'unsigned'
		public Keyword getUnsignedKeyword_5_1() { return cUnsignedKeyword_5_1; }
		
		//'long'
		public Keyword getLongKeyword_5_2() { return cLongKeyword_5_2; }
		
		//'long'
		public Keyword getLongKeyword_5_3() { return cLongKeyword_5_3; }
		
		//{FloatType} 'float'
		public Group getGroup_6() { return cGroup_6; }
		
		//{FloatType}
		public Action getFloatTypeAction_6_0() { return cFloatTypeAction_6_0; }
		
		//'float'
		public Keyword getFloatKeyword_6_1() { return cFloatKeyword_6_1; }
		
		//{DoubleType} 'double'
		public Group getGroup_7() { return cGroup_7; }
		
		//{DoubleType}
		public Action getDoubleTypeAction_7_0() { return cDoubleTypeAction_7_0; }
		
		//'double'
		public Keyword getDoubleKeyword_7_1() { return cDoubleKeyword_7_1; }
		
		//{LongDoubleType} 'long' 'double'
		public Group getGroup_8() { return cGroup_8; }
		
		//{LongDoubleType}
		public Action getLongDoubleTypeAction_8_0() { return cLongDoubleTypeAction_8_0; }
		
		//'long'
		public Keyword getLongKeyword_8_1() { return cLongKeyword_8_1; }
		
		//'double'
		public Keyword getDoubleKeyword_8_2() { return cDoubleKeyword_8_2; }
		
		//{CharType} 'char'
		public Group getGroup_9() { return cGroup_9; }
		
		//{CharType}
		public Action getCharTypeAction_9_0() { return cCharTypeAction_9_0; }
		
		//'char'
		public Keyword getCharKeyword_9_1() { return cCharKeyword_9_1; }
		
		//{WideCharType} 'wchar'
		public Group getGroup_10() { return cGroup_10; }
		
		//{WideCharType}
		public Action getWideCharTypeAction_10_0() { return cWideCharTypeAction_10_0; }
		
		//'wchar'
		public Keyword getWcharKeyword_10_1() { return cWcharKeyword_10_1; }
		
		//{BooleanType} 'boolean'
		public Group getGroup_11() { return cGroup_11; }
		
		//{BooleanType}
		public Action getBooleanTypeAction_11_0() { return cBooleanTypeAction_11_0; }
		
		//'boolean'
		public Keyword getBooleanKeyword_11_1() { return cBooleanKeyword_11_1; }
		
		//{OctetType} 'octet'
		public Group getGroup_12() { return cGroup_12; }
		
		//{OctetType}
		public Action getOctetTypeAction_12_0() { return cOctetTypeAction_12_0; }
		
		//'octet'
		public Keyword getOctetKeyword_12_1() { return cOctetKeyword_12_1; }
		
		//{ReferencedType} type=[Definition|ScopedName]
		public Group getGroup_13() { return cGroup_13; }
		
		//{ReferencedType}
		public Action getReferencedTypeAction_13_0() { return cReferencedTypeAction_13_0; }
		
		//type=[Definition|ScopedName]
		public Assignment getTypeAssignment_13_1() { return cTypeAssignment_13_1; }
		
		//[Definition|ScopedName]
		public CrossReference getTypeDefinitionCrossReference_13_1_0() { return cTypeDefinitionCrossReference_13_1_0; }
		
		//ScopedName
		public RuleCall getTypeDefinitionScopedNameParserRuleCall_13_1_0_1() { return cTypeDefinitionScopedNameParserRuleCall_13_1_0_1; }
	}
	public class ScopedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.ScopedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cColonColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		///*
		// * (4) <scoped_name> ::= <identifier>
		// *                   | "::" <identifier>
		// *                   | <scoped_name> "::" <identifier>
		// */ ScopedName:
		//	'::'? (ID '::')* ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'::'? (ID '::')* ID
		public Group getGroup() { return cGroup; }
		
		//'::'?
		public Keyword getColonColonKeyword_0() { return cColonColonKeyword_0; }
		
		//(ID '::')*
		public Group getGroup_1() { return cGroup_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_0() { return cIDTerminalRuleCall_1_0; }
		
		//'::'
		public Keyword getColonColonKeyword_1_1() { return cColonColonKeyword_1_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2() { return cIDTerminalRuleCall_2; }
	}
	
	
	private final SpecificationElements pSpecification;
	private final DefinitionElements pDefinition;
	private final MemberElements pMember;
	private final CaseElements pCase;
	private final FixedArraySizeElements pFixedArraySize;
	private final TypeElements pType;
	private final SimpleTypeSpecElements pSimpleTypeSpec;
	private final ScopedNameElements pScopedName;
	private final TerminalRule tID;
	private final TerminalRule tPREPROCESSOR;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SimpleIDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSpecification = new SpecificationElements();
		this.pDefinition = new DefinitionElements();
		this.pMember = new MemberElements();
		this.pCase = new CaseElements();
		this.pFixedArraySize = new FixedArraySizeElements();
		this.pType = new TypeElements();
		this.pSimpleTypeSpec = new SimpleTypeSpecElements();
		this.pScopedName = new ScopedNameElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.ID");
		this.tPREPROCESSOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.osate.simpleidl.SimpleIDL.PREPROCESSOR");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.osate.simpleidl.SimpleIDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*
	// * This is a subset of IDL 4.2. It is intended to be used to parse IDL files generated from the FACE Conformance Test
	// * Suite 3.0. Portions of IDL which are not generated by the FACE CTS are not included in this subset.
	// * 
	// * In one case, FACE's version of IDL in the FACE standard disagrees with the IDL standard. In FACE, a union has an
	// * opening curly between the union's name and the "switch" keyword. It also has a corresponding closing curly and
	// * semicolon at the end of the union. These are not in the IDL standard. This subset follows the FACE standard for
	// * unions and deviates from the IDL standard.
	// * 
	// * The comments on each grammar rule in this file contain the relevant syntax definitions from the IDL standard's
	// * Annex A: Consolidated IDL Grammar.
	// */ /*
	// * (1) <specification> ::= <definition>+
	// */ Specification:
	//	definitions+=Definition+;
	public SpecificationElements getSpecificationAccess() {
		return pSpecification;
	}
	
	public ParserRule getSpecificationRule() {
		return getSpecificationAccess().getRule();
	}
	
	///*
	// * (2) <definition> ::= <module_dcl> ";"
	// *                  | <const_dcl> ";"
	// *                  | <type_dcl> ";"
	// * (3) <module_dcl> ::= "module" <identifier> "{" <definition>+ "}"
	// * (20) <type_dcl> ::= <constr_type_dcl>
	// *                 | <native_dcl>
	// *                 | <typedef_dcl>
	// * (44) <constr_type_dcl> ::= <struct_dcl>
	// *                        | <union_dcl>
	// *                        | <enum_dcl>
	// * (45) <struct_dcl> ::= <struct_def>
	// *                   | <struct_forward_dcl>
	// * (46) <struct_def> ::= "struct" <identifier> "{" <member>+ "}"
	// * (48) <struct_forward_dcl> ::= "struct" <identifier>
	// * (49) <union_dcl> ::= <union_def>
	// *                  | <union_forward_dcl>
	// * (50) <union_def> ::= "union" <identifier> "switch" "(" <switch_type_spec> ")"
	// *                      "{" <switch_body> "}"
	// * (51) <switch_type_spec> ::= <integer_type>
	// *                         | <char_type>
	// *                         | <boolean_type>
	// *                         | <scoped_name>
	// * (52) <switch_body> ::= <case>+
	// * (57) <enum_dcl> ::= "enum" <identifier>
	// *                     "{" <enumerator> { "," <enumerator> } * "}"
	// * (58) <enumerator> ::= <identifier>
	// * (59) <array_declarator> ::= <identifier> <fixed_array_size>+
	// * (62) <simple_declarator> ::= <identifier>
	// * (63) <typedef_dcl> ::= "typedef" <type_declarator>
	// * (64) <type_declarator> ::= { <simple_type_spec>
	// *                            | <template_type_spec>
	// *                            | <constr_type_dcl>
	// *                            } <any_declarators>
	// * (65) <any_declarators> ::= <any_declarator> { "," <any_declarator> }*
	// * (66) <any_declarator> ::= <simple_declarator>
	// *                       | <array_declarator>
	// */ Definition:
	//	{Module} 'module' name=ID '{' definitions+=Definition+ '}' ';' | {Struct} 'struct' name=ID '{' members+=Member+ '}'
	//	';' | {StructForward} 'struct' struct=[Struct] ';' | {Union} 'union' name=ID '{' 'switch' '(' 'unsigned' 'short' ')'
	//	'{' cases+=Case+ '}' ';' '}' ';' | {Enum} 'enum' name=ID '{' literals+=ID (',' literals+=ID)* '}' ';' | {Typedef}
	//	'typedef' type=Type name=ID arraySize=FixedArraySize? ';';
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}
	
	///*
	// * (21) <type_spec> ::= <simple_type_spec>
	// * (47) <member> ::= <type_spec> <declarators> ";"
	// * (62) <simple_declarator> ::= <identifier>
	// * (67) <declarators> ::= <declarator> { "," <declarator> }*
	// * (68) <declarator> ::= <simple_declarator>
	// */ Member:
	//	type=SimpleTypeSpec name=ID ';';
	public MemberElements getMemberAccess() {
		return pMember;
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}
	
	///*
	// * (21) <type_spec> ::= <simple_type_spec>
	// * (53) <case> ::= <case_label>+ <element_spec> ";"
	// * (54) <case_label> ::= "case" <const_expr> ":"
	// *                   | "default" ":"
	// * (55) <element_spec> ::= <type_spec> <declarator>
	// * (62) <simple_declarator> ::= <identifier>
	// * (68) <declarator> ::= <simple_declarator>
	// */ Case:
	//	('case' labels+=INT ':')+ type=SimpleTypeSpec name=ID ';';
	public CaseElements getCaseAccess() {
		return pCase;
	}
	
	public ParserRule getCaseRule() {
		return getCaseAccess().getRule();
	}
	
	///*
	// * (60) <fixed_array_size> ::= "[" <positive_int_const> "]"
	// */ FixedArraySize:
	//	'[' size=INT ']';
	public FixedArraySizeElements getFixedArraySizeAccess() {
		return pFixedArraySize;
	}
	
	public ParserRule getFixedArraySizeRule() {
		return getFixedArraySizeAccess().getRule();
	}
	
	///*
	// * (21) <type_spec> ::= <simple_type_spec>
	// * (38) <template_type_spec> ::= <sequence_type>
	// *                           | <string_type>
	// *                           | <wide_string_type>
	// *                           | <fixed_pt_type>
	// * (39) <sequence_type> ::= "sequence" "<" <type_spec> "," <positive_int_const> ">"
	// *                      | "sequence" "<" <type_spec> ">"
	// * (40) <string_type> ::= "string" "<" <positive_int_const> ">"
	// *                    | "string"
	// * (41) <wide_string_type> ::= "wstring" "<" <positive_int_const> ">"
	// *                         | "wstring"
	// * (42) <fixed_pt_type> ::= "fixed" "<" <positive_int_const> "," <positive_int_const> ">"
	// * (64) <type_declarator> ::= { <simple_type_spec>
	// *                            | <template_type_spec>
	// *                            | <constr_type_dcl>
	// *                            } <any_declarators>
	// */ Type:
	//	SimpleTypeSpec | {BoundedSequence} 'sequence' '<' type=SimpleTypeSpec ',' size=INT '>' | {UnboundedSequence}
	//	'sequence' '<' type=SimpleTypeSpec '>' | {BoundedString} 'string' '<' size=INT '>' | {UnboundedString} 'string' |
	//	{BoundedWideString} 'wstring' '<' size=INT '>' | {UnboundedWideString} 'wstring' | {FixedPtType} 'fixed' '<'
	//	totalDigits=INT ',' fractionalDigits=INT '>';
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	///*
	// * (22) <simple_type_spec> ::= <base_type_spec>
	// *                         | <scoped_name>
	// * (23) <base_type_spec> ::= <integer_type>
	// *                       | <floating_pt_type>
	// *                       | <char_type>
	// *                       | <wide_char_type>
	// *                       | <boolean_type>
	// *                       | <octet_type>
	// * (24) <floating_pt_type> ::= "float"
	// *                         | "double"
	// *                         | "long" "double"
	// * (25) <integer_type> ::= <signed_int>
	// *                     | <unsigned_int>
	// * (26) <signed_int> ::= <signed_short_int>
	// *                   | <signed_long_int>
	// *                   | <signed_longlong_int>
	// * (27) <signed_short_int> ::= "short"
	// * (28) <signed_long_int> ::= "long"
	// * (29) <signed_longlong_int> ::= "long" "long"
	// * (30) <unsigned_int> ::= <unsigned_short_int>
	// *                     | <unsigned_long_int>
	// *                     | <unsigned_longlong_int>
	// * (31) <unsigned_short_int> ::= "unsigned" "short"
	// * (32) <unsigned_long_int> ::= "unsigned" "long"
	// * (33) <unsigned_longlong_int> ::= "unsigned" "long" "long"
	// * (34) <char_type> ::= "char"
	// * (35) <wide_char_type> ::= "wchar"
	// * (36) <boolean_type> ::= "boolean"
	// * (37) <octet_type> ::= "octet"
	// */ SimpleTypeSpec:
	//	{SignedShortInt} 'short' | {SignedLongInt} 'long' | {SignedLongLongInt} 'long' 'long' | {UnsignedShortInt} 'unsigned'
	//	'short' | {UnsignedLongInt} 'unsigned' 'long' | {UnsignedLongLongInt} 'unsigned' 'long' 'long' | {FloatType} 'float' |
	//	{DoubleType} 'double' | {LongDoubleType} 'long' 'double' | {CharType} 'char' | {WideCharType} 'wchar' | {BooleanType}
	//	'boolean' | {OctetType} 'octet' | {ReferencedType} type=[Definition|ScopedName];
	public SimpleTypeSpecElements getSimpleTypeSpecAccess() {
		return pSimpleTypeSpec;
	}
	
	public ParserRule getSimpleTypeSpecRule() {
		return getSimpleTypeSpecAccess().getRule();
	}
	
	///*
	// * (4) <scoped_name> ::= <identifier>
	// *                   | "::" <identifier>
	// *                   | <scoped_name> "::" <identifier>
	// */ ScopedName:
	//	'::'? (ID '::')* ID;
	public ScopedNameElements getScopedNameAccess() {
		return pScopedName;
	}
	
	public ParserRule getScopedNameRule() {
		return getScopedNameAccess().getRule();
	}
	
	//@Override
	//terminal ID:
	//	('a'..'z' | 'A'..'Z') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal PREPROCESSOR:
	//	('#define' | '#endif' | '#ifndef' | '#include') !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getPREPROCESSORRule() {
		return tPREPROCESSOR;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
